#### **CORRECTITUD DE DATOS**

In [1]:
import pandas as pd 
import numpy as np

catalogo_productos = pd.read_csv("Datos-finales/catalogo_productos.csv")
especificaciones_cajas = pd.read_csv("Datos-finales/especificaciones_cajas.csv")
operaciones_planta = pd.read_csv("Datos-finales/operaciones_planta.csv")
procurement_cajas = pd.read_csv("Datos-finales/procurement_cajas.csv")

Creamos una función que nos permita verificar la correctitud de los datos. La idea es calcular manualmente las filas de una columna específica y luego compararla con las de la existente.

In [2]:
def verificar_correctitud(df, col1, col2):
    df = df.copy()
    df['coincide'] = np.isclose(df[col1], df[col2])
    
    # Filtrar las que no coinciden
    no_coinciden = df[df['coincide'] == False]
    
    if no_coinciden.empty:
        print("TODAS LAS FILAS COINCIDEN.")
        return None
    else:
        print(f"{len(no_coinciden)} FILAS NO coinciden")
        return no_coinciden[[col1, col2, 'coincide']]

In [3]:
especificaciones_cajas['caja_exterior_largo_calculado'] = (
    especificaciones_cajas['caja_interior_largo'] + 
    2 * especificaciones_cajas['caja_grosor_mm']
)

especificaciones_cajas['caja_exterior_ancho_calculado'] = (
    especificaciones_cajas['caja_interior_ancho'] + 
    2 * especificaciones_cajas['caja_grosor_mm']
)

especificaciones_cajas['caja_exterior_alto_calculado'] = (
    especificaciones_cajas['caja_interior_alto'] + 
    2 * especificaciones_cajas['caja_grosor_mm']
)

verificar_correctitud(especificaciones_cajas, 'caja_exterior_largo', 
                                'caja_exterior_largo_calculado')

print("-" * 30)
verificar_correctitud(especificaciones_cajas, 'caja_exterior_ancho', 
                                'caja_exterior_ancho_calculado')
print("-" * 30)
verificar_correctitud(especificaciones_cajas, 'caja_exterior_alto', 
                                'caja_exterior_alto_calculado')

TODAS LAS FILAS COINCIDEN.
------------------------------
TODAS LAS FILAS COINCIDEN.
------------------------------
TODAS LAS FILAS COINCIDEN.

In [4]:
operaciones_planta['volumen_producto_total_calculado'] = (
    operaciones_planta['volumen_producto_canal_servicios_comida'] +
    operaciones_planta['volumen_producto_canal_minorista'] +
    operaciones_planta['volumen_producto_canal_cadenas_corporativas'] +
    operaciones_planta['volumen_producto_canal_otros']
)

verificar_correctitud(operaciones_planta, 'volumen_producto_total', 
                                'volumen_producto_total_calculado')

TODAS LAS FILAS COINCIDEN.

In [5]:
operaciones_planta['volumen_producto_total_calculado2'] = (
    operaciones_planta['volumen_producto_planta_buenos_aires'] +
    operaciones_planta['volumen_producto_planta_curitiba'] +
    operaciones_planta['volumen_producto_planta_santiago'] +
    operaciones_planta['volumen_producto_planta_monterrey'] +
    operaciones_planta['volumen_producto_planta_bakersfield']
)

verificar_correctitud(operaciones_planta, 'volumen_producto_total', 
                                'volumen_producto_total_calculado2')

TODAS LAS FILAS COINCIDEN.

In [6]:
operaciones_planta['cantidad_pallets_total_calculado'] = (
    operaciones_planta['cantidad_pallets_planta_buenos_aires'] +
    operaciones_planta['cantidad_pallets_planta_curitiba'] +
    operaciones_planta['cantidad_pallets_planta_santiago'] +
    operaciones_planta['cantidad_pallets_planta_monterrey'] +
    operaciones_planta['cantidad_pallets_planta_bakersfield']
)

verificar_correctitud(operaciones_planta, 'cantidad_pallets_total',
                                'cantidad_pallets_total_calculado')

TODAS LAS FILAS COINCIDEN.

In [7]:
operaciones_planta['costo_pallets_total_calculado'] = (
    operaciones_planta['costo_pallets_planta_buenos_aires'] +
    operaciones_planta['costo_pallets_planta_curitiba'] +
    operaciones_planta['costo_pallets_planta_santiago'] +
    operaciones_planta['costo_pallets_planta_monterrey'] +
    operaciones_planta['costo_pallets_planta_bakersfield']
)

verificar_correctitud(operaciones_planta, 'costo_pallets_total',
                                'costo_pallets_total_calculado')

TODAS LAS FILAS COINCIDEN.

In [8]:
operaciones_planta['costo_total_calculado'] = (
    operaciones_planta['costo_total_planta_buenos_aires'] +
    operaciones_planta['costo_total_planta_curitiba'] +
    operaciones_planta['costo_total_planta_santiago'] +
    operaciones_planta['costo_total_planta_monterrey'] +
    operaciones_planta['costo_total_planta_bakersfield']
)

verificar_correctitud(operaciones_planta, 'costo_total',
                                'costo_total_calculado')

TODAS LAS FILAS COINCIDEN.

In [9]:
operaciones_planta['costo_pallets_planta_buenos_aires_calculado'] = (
    150 * operaciones_planta['cantidad_pallets_planta_buenos_aires']
) 

operaciones_planta['costo_pallets_planta_curitiba_calculado'] = (
    150 * operaciones_planta['cantidad_pallets_planta_curitiba']
) 

operaciones_planta['costo_pallets_planta_santiago_calculado'] = (
    150 * operaciones_planta['cantidad_pallets_planta_santiago']
) 

operaciones_planta['costo_pallets_planta_monterrey_calculado'] = (
    150 * operaciones_planta['cantidad_pallets_planta_monterrey']
) 

operaciones_planta['costo_pallets_planta_bakersfield_calculado'] = (
    150 * operaciones_planta['cantidad_pallets_planta_bakersfield']
) 

verificar_correctitud(operaciones_planta, 'costo_pallets_planta_buenos_aires',
                                'costo_pallets_planta_buenos_aires_calculado')
print("-" * 30)
verificar_correctitud(operaciones_planta, 'costo_pallets_planta_curitiba',
                                'costo_pallets_planta_curitiba_calculado')
print("-" * 30)
verificar_correctitud(operaciones_planta, 'costo_pallets_planta_santiago',
                                'costo_pallets_planta_santiago_calculado')
print("-" * 30)
verificar_correctitud(operaciones_planta, 'costo_pallets_planta_monterrey',
                                'costo_pallets_planta_monterrey_calculado')
print("-" * 30)
verificar_correctitud(operaciones_planta, 'costo_pallets_planta_bakersfield',
                                'costo_pallets_planta_bakersfield_calculado')

TODAS LAS FILAS COINCIDEN.
------------------------------
TODAS LAS FILAS COINCIDEN.
------------------------------
TODAS LAS FILAS COINCIDEN.
------------------------------
TODAS LAS FILAS COINCIDEN.
------------------------------
TODAS LAS FILAS COINCIDEN.

In [10]:
# Hacemos un merge de la tabla de producto con la de caja
df_merge = catalogo_productos.merge(
    operaciones_planta,
    on='codigo_producto'  # hacemos un join por la clave de caja
)

df_merge = df_merge.merge(
    procurement_cajas,
    on='caja_tipo_id',  # hacemos un join por la clave de caja
    how='left'          # dos productos distintos pueden usar la misma caja
)

In [11]:
df_merge['costo_total_planta_buenos_aires_calculado'] = (
    df_merge['volumen_producto_planta_buenos_aires'] *
    df_merge['costo_unitario_planta_buenos_aires']
)

verificar_correctitud(df_merge, 'costo_total_planta_buenos_aires',
                                'costo_total_planta_buenos_aires_calculado')

63 FILAS NO coinciden

,costo_total_planta_buenos_aires,costo_total_planta_buenos_aires_calculado,coincide
7,9222.570,8197.84,False
19,41172.300,36597.60,False
20,22503.040,19690.16,False
21,9585.550,7668.44,False
26,46081.840,40321.61,False
...,...,...,...
394,11520.900,10240.80,False
400,10630.980,9449.76,False
424,8780.200,7024.16,False
425,5454.020,4958.20,False
426,25.025,22.75,False

El problema está en el costo unitario: (hay que recalcular)

In [12]:
plantas = ['buenos_aires', 'curitiba', 'santiago', 'monterrey', 'bakersfield']  

resultados = {}

for planta in plantas:
    col_volumen = f'volumen_producto_planta_{planta}'
    col_costo_total = f'costo_total_planta_{planta}'
    col_costo_total_calc = f'costo_total_planta_{planta}_calculado'
    col_costo_unit = f'costo_unitario_planta_{planta}'
    
    # Chequeo 1: costo unitario vs (costo_total / volumen)
    calculables = df_merge[df_merge[col_volumen] > 0]
    costo_unit = calculables[col_costo_total] / calculables[col_volumen]
    inconsistentes_unit = calculables[~np.isclose(costo_unit, calculables[col_costo_unit])]
    
    # Chequeo 2: costo_total vs costo_total_calculado
    ids = df_merge[~np.isclose(df_merge[col_costo_total], 
                                 df_merge[col_costo_total_calc])]['caja_tipo_id']
    
    print(f'--- {planta} ---')
    print(f'Inconsistencias costo unitario: {inconsistentes_unit.shape[0]}')
    print(f'Inconsistencias costo total: {ids.shape[0]}')
    

    print()
    
    resultados[planta] = {
        'inconsistentes_unitario': inconsistentes_unit,
        'ids_costo_total': ids
    }

--- buenos_aires ---
Inconsistencias costo unitario: 63
Inconsistencias costo total: 63

KeyError: 'costo_total_planta_curitiba_calculado'

In [ ]:
procurement_cajas.columns

Index(['caja_tipo_id', 'volumen_tipo_planta_buenos_aires',
       'volumen_tipo_planta_curitiba', 'volumen_tipo_planta_santiago',
       'volumen_tipo_planta_monterrey', 'volumen_tipo_planta_bakersfield',
       'costo_unitario_base', 'costo_total_base',
       'costo_unitario_planta_buenos_aires', 'costo_unitario_planta_curitiba',
       'costo_unitario_planta_santiago', 'costo_unitario_planta_monterrey',
       'costo_unitario_planta_bakersfield', 'descuento_planta_buenos_aires',
       'descuento_planta_curitiba', 'descuento_planta_santiago',
       'descuento_planta_monterrey', 'descuento_planta_bakersfield',
       'costo_por_pallet', 'descuento_planta_buenos_aires_original',
       'descuento_planta_curitiba_original',
       'descuento_planta_santiago_original',
       'descuento_planta_monterrey_original',
       'descuento_planta_bakersfield_original'],
      dtype='str')

In [ ]:
ids_grosor_48

,caja_tipo_id,caja_grosor_mm,caja_interior_largo,caja_interior_ancho,caja_interior_alto,caja_exterior_largo,caja_exterior_ancho,caja_exterior_alto,pallet_alto,pallet_ancho,pallet_largo,cantidad_cajas_alto,cantidad_cajas_largo,cantidad_cajas_ancho,cantidad_cajas_total,utilizacion,caja_exterior_largo_calculado,caja_exterior_ancho_calculado,caja_exterior_alto_calculado
0,016d196c89dcfcb306b853a776a879b9,4.8,383.0,248.0,224.0,392.6,257.6,233.6,1800,800,1200,7.0,2.0,4.0,56.0,0.765620,392.6,257.6,233.6
3,02d7c6680102bd11e067c00c9b71ab9c,4.8,383.0,248.0,268.0,392.6,257.6,277.6,1800,800,1200,6.0,2.0,4.0,48.0,0.779854,392.6,257.6,277.6
9,0a3dd3e01e43d4796c7cf1e84a70c57e,4.8,385.0,255.0,318.0,394.6,264.6,327.6,1800,800,1200,5.0,2.0,4.0,40.0,0.791785,394.6,264.6,327.6
10,0b1eab65d0cf634954fecfe2e9f2b337,4.8,386.0,285.0,283.0,395.6,294.6,292.6,1800,800,1200,6.0,2.0,4.0,48.0,0.947242,395.6,294.6,292.6
17,1235d2c994be7bb77d7eef060ecf96f6,4.8,383.0,248.0,194.0,392.6,257.6,203.6,1800,800,1200,8.0,2.0,4.0,64.0,0.762623,392.6,257.6,203.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185,eb35ea3a60188f7974c4d3e95df76b3e,4.8,386.0,285.0,192.0,395.6,294.6,201.6,1800,800,1200,8.0,2.0,4.0,64.0,0.870193,395.6,294.6,201.6
188,ecf787428007d25a0f29d1b250a67a26,4.8,386.0,285.0,244.0,395.6,294.6,253.6,1800,800,1200,7.0,2.0,4.0,56.0,0.957817,395.6,294.6,253.6
195,f46de34159e1d0d6a5dfd38017585c4e,4.8,386.0,285.0,268.0,395.6,294.6,277.6,1800,800,1200,6.0,2.0,4.0,48.0,0.898682,395.6,294.6,277.6
197,f5bd804a90f4512d522129ccb62d549f,4.8,379.0,268.0,358.0,388.6,277.6,367.6,1800,800,1200,4.0,2.0,4.0,32.0,0.734352,388.6,277.6,367.6
202,fce36b1b860f566c05d3e06484e6f4e2,4.8,388.0,287.0,194.0,397.6,296.6,203.6,1800,800,1200,8.0,2.0,4.0,64.0,0.889266,397.6,296.6,203.6

In [ ]:
ids_grosor_48 = especificaciones_cajas[especificaciones_cajas['caja_grosor_mm'] == 4.8]

procurement_cajas[procurement_cajas['caja_tipo_id'].isin(ids_grosor_48)]['costo_unitario_base']

Series([], Name: costo_unitario_base, dtype: float64)

In [ ]:
calculables = df_merge[df_merge['volumen_producto_planta_buenos_aires']  > 0]

costo_unit = calculables['costo_total_planta_buenos_aires'] /  calculables['volumen_producto_planta_buenos_aires']

calculables[~np.isclose(costo_unit, calculables['costo_unitario_planta_buenos_aires'])]

,codigo_producto,descripcion_producto,ingrediente_forma,tipo_proyecto,subcategoria,categoria,tamaño_corte,peso_neto_caja,tamaño_paquete,cantidad_paquetes,...,descuento_planta_buenos_aires_original,descuento_planta_curitiba_original,descuento_planta_santiago_original,descuento_planta_monterrey_original,descuento_planta_bakersfield_original,costo_total_planta_buenos_aires_calculado,costo_total_planta_curitiba_calculado,costo_total_planta_santiago_calculado,costo_total_planta_monterrey_calculado,costo_total_planta_bakersfield_calculado
7,BR0008,11 bolsas de 1 kg | Bastones rectos de brocoli...,Bastones rectos de brocoli,Estacional,Bastones clasicos - Legumes Frites,Bastones clasicos,Medio,11.00,11 X 1 KG,11,...,-10%,+10%,+10%,+0%,-20 %,8197.84,0.00,0.000,0.000,0.000
19,BR0020,Bastones rectos de brocoli 9x9 mm - clasico - ...,Bastones rectos de brocoli,Estacional,Bastones clasicos - Legumes Frites,Bastones clasicos,Medio,12.50,"5 X 2,5 KG",5,...,-10%,-20%,+10%,-30%,+10%,36597.60,0.00,0.000,9700.145,0.000
20,BR0021,"5 bolsas de 2,5 kg | Bastones rectos de brocol...",Bastones rectos de brocoli,Estacional,Bastones clasicos - Legumes Frites,Bastones clasicos,Corte steak,12.50,"5 X 2,5 KG",5,...,-20,+10%,+10%,-20%,-10%,19690.16,0.00,0.000,0.000,0.000
21,BR0022,BonsaiGreen Bastones rectos de brocoli 7x7 mm ...,Bastones rectos de brocoli,Estacional,Bastones clasicos - Legumes Frites,Bastones clasicos,Fino,12.50,"5 X 2,5 KG",5,...,+0%,+0%,+0%,+ 0%,+10%,7668.44,0.00,0.000,0.000,0.000
26,BR0027,BonsaiGreen Bastones rectos de brocoli 11x11 m...,Bastones rectos de brocoli,Estacional,Bastones clasicos - Mayordomo,Bastones clasicos,Medio,12.50,"5 X 2,5 KG",5,...,-20%,10,+10%,"+10,00%",+10%,40321.61,0.00,0.000,0.000,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,BR0353,"BonsaiVegetales Croquetas de brocoli 13 x 0,75 kg",Croquetas de brocoli,Forma estable,Guarniciones - Legumes Croquetas,Guarniciones,Forma,9.75,"13 X 0,75 KG",13,...,-10%,+10%,+ 10%,+10%,10%,10240.80,0.00,0.000,0.000,0.000
400,BR0359,Brocoli zigzag - clasico - Caja de 13 packs de...,Brocoli zigzag,Forma estable,Bastones clasicos - Legumes Frites,Bastones clasicos,Forma,9.75,"5 X 2,5 kg",13,...,-10,+10%,+10%,+10%,+10,9449.76,0.00,0.000,0.000,0.000
424,BR0383,BonsaiGreen Bastones rectos de brocoli 9x9 mm ...,Bastones rectos de brocoli,Estacional,Bastones clasicos - Grado B,Bastones clasicos,Medio,12.50,"5 X 2,5 KG",5,...,+0%,+0%,+0%,+ 0%,+10%,7024.16,0.00,0.000,1523.080,0.000
425,BR0384,"5 bolsas de 2,5 kg | Bastones rectos de brocol...",Bastones rectos de brocoli,Estacional,Bastones clasicos - Grado B,Bastones clasicos,Medio,12.50,"5 X2,5 KG",5,...,+10%,+10%,+10%,-10%,+10%,4958.20,0.00,0.000,6678.360,0.000
426,BR0385,"5 bolsas de 2,5 kg | Bastones rectos de brocol...",Bastones rectos de brocoli,Estacional,Bastones clasicos - Grado B,Bastones clasicos,Medio,12.50,"5 X 2,5 KG",5,...,+10%,+10%,+10%,-10%,+10%,22.75,51.35,36.465,13.520,22.165

In [ ]:
ids = df_merge[~np.isclose(df_merge['costo_total_planta_buenos_aires'], 
                      df_merge['costo_total_planta_buenos_aires_calculado'])]['caja_tipo_id']

print(ids.shape)
especificaciones_cajas[especificaciones_cajas['caja_tipo_id'].isin(ids)]['caja_grosor_mm'].value_counts()

(63,)

caja_grosor_mm
4.1    10
4.8     7
2.7     6
4.7     2
Name: count, dtype: int64

In [ ]:
df_merge['costo_total_planta_curitiba_calculado'] = (
    df_merge['volumen_producto_planta_curitiba'] *
    df_merge['costo_unitario_planta_curitiba']
)

verificar_correctitud(df_merge, 'costo_total_planta_curitiba',
                                'costo_total_planta_curitiba_calculado')

95 FILAS NO coinciden

,costo_total_planta_curitiba,costo_total_planta_curitiba_calculado,coincide
1,72389.720,63341.005,False
6,27405.495,24360.440,False
12,79691.040,69729.660,False
16,68535.480,59968.545,False
22,8698.410,7731.920,False
...,...,...,...
438,251862.520,220379.705,False
439,39882.080,34896.820,False
442,4745.520,4218.240,False
453,508.410,451.920,False
461,12598.040,11023.285,False

In [ ]:
df_merge['costo_total_planta_santiago_calculado'] = (
    df_merge['volumen_producto_planta_santiago'] *
    df_merge['costo_unitario_planta_santiago']
)

verificar_correctitud(df_merge, 'costo_total_planta_santiago',
                                'costo_total_planta_santiago_calculado')

94 FILAS NO coinciden

,costo_total_planta_santiago,costo_total_planta_santiago_calculado,coincide
0,18608.10,16747.29,False
8,3228.61,2935.10,False
36,38691.90,34392.80,False
67,28097.30,22477.84,False
75,5242.90,4194.32,False
...,...,...,...
455,40.04,36.40,False
456,29.68,25.97,False
457,38.50,35.00,False
458,2125.97,1932.70,False
459,3035.34,2759.40,False

In [ ]:
df_merge['costo_total_planta_monterrey_calculado'] = (
    df_merge['volumen_producto_planta_monterrey'] *
    df_merge['costo_unitario_planta_monterrey']
)

verificar_correctitud(df_merge, 'costo_total_planta_monterrey',
                                'costo_total_planta_monterrey_calculado')

37 FILAS NO coinciden

,costo_total_planta_monterrey,costo_total_planta_monterrey_calculado,coincide
0,55618.920,49439.040,False
8,1182.720,1034.880,False
24,53658.640,46951.310,False
25,28646.800,22917.440,False
68,24923.925,22154.600,False
75,2905.045,2376.855,False
89,33503.400,29780.800,False
90,24542.000,22087.800,False
92,57198.960,44488.080,False
93,45363.955,58325.085,False
104,36033.200,31529.050,False
184,1562.275,1278.225,False
185,230.945,188.955,False
186,5729.750,5156.775,False
188,2902.900,2375.100,False
189,2715.570,2221.830,False
287,37694.720,32982.880,False
291,89306.560,78143.240,False
292,30655.800,24524.640,False
327,11547.900,10393.110,False
333,7055.620,6414.200,False
334,7807.800,7098.000,False
337,4291.950,3862.755,False
338,4315.350,3883.815,False
339,7569.250,6812.325,False
345,12382.370,11256.700,False
350,156618.000,137040.750,False
423,19635.200,15708.160,False
424,1903.850,1523.080,False
425,7513.155,6678.360,False
426,15.210,13.520,False
446,14.000,12.250,False
447,15.750,14.000,False
449,16.380,14.560,False
455,15.120,13.230,False
457,14.000,12.250,False
460,28145.000,25330.500,False

In [ ]:
df_merge['costo_total_planta_bakersfield_calculado'] = (
    df_merge['volumen_producto_planta_bakersfield'] *
    df_merge['costo_unitario_planta_bakersfield']
)

verificar_correctitud(df_merge, 'costo_total_planta_bakersfield',
                                'costo_total_planta_bakersfield_calculado')

50 FILAS NO coinciden

,costo_total_planta_bakersfield,costo_total_planta_bakersfield_calculado,coincide
2,96603.360,84527.940,False
3,141291.800,123630.325,False
8,1920.380,1745.800,False
11,157850.000,138118.750,False
17,101679.760,88969.790,False
64,53924.640,47184.060,False
72,16147.040,14128.660,False
75,3430.570,2494.960,False
136,32452.550,25962.040,False
184,1844.700,1341.600,False
185,272.415,198.120,False
186,6767.150,6090.435,False
188,3428.425,2493.400,False
189,3207.490,2332.720,False
203,59083.920,52519.040,False
204,45924.320,40183.780,False
205,43151.680,37757.720,False
206,45924.320,40183.780,False
207,43151.680,37757.720,False
226,1451.520,1270.080,False
227,2161.390,1375.430,False
228,1451.520,1995.840,False
230,34193.040,29918.910,False
231,26649.280,23318.120,False
316,41263.740,36678.880,False
319,21906.560,19168.240,False
327,13638.300,12274.470,False
333,8332.610,7575.100,False
334,9220.640,8382.400,False
337,5068.700,4561.830,False
338,5096.650,4586.985,False
339,8939.450,8045.505,False
340,245042.000,214411.750,False
341,238938.560,209071.240,False
353,37285.920,33143.040,False
379,59921.680,52431.470,False
380,59012.800,51636.200,False
381,59921.680,52431.470,False
382,59012.800,51636.200,False
388,213760.960,187040.840,False
408,32143.860,28572.320,False
411,52811.720,46210.255,False
415,11437.140,9357.660,False
416,134958.880,118089.020,False
442,9329.320,8481.200,False
443,12484.780,11349.800,False
446,23.100,21.000,False
454,1127.840,986.860,False
455,23.870,21.700,False
457,23.100,21.000,False

In [ ]:
df_merge

,codigo_producto,descripcion_producto,ingrediente_forma,tipo_proyecto,subcategoria,categoria,tamaño_corte,peso_neto_caja,tamaño_paquete,cantidad_paquetes,...,descuento_planta_buenos_aires_original,descuento_planta_curitiba_original,descuento_planta_santiago_original,descuento_planta_monterrey_original,descuento_planta_bakersfield_original,costo_total_planta_buenos_aires_calculado,costo_total_planta_curitiba_calculado,costo_total_planta_santiago_calculado,costo_total_planta_monterrey_calculado,costo_total_planta_bakersfield_calculado
0,BR0001,"5 bolsas de 2,5 kg | Bastones rectos de brocol...",Bastones rectos de brocoli,Estacional,Bastones clasicos - Reserva Privada,Bastones clasicos,Fino,12.50,"5 X 2,5 KG",5,...,+10%,-30%,+0%,-10%,+10%,0.0,701555.540,16747.29,49439.040,0.000
1,BR0002,Espirales de brocoli - clasico - Caja de 13 pa...,Espirales de brocoli,Forma estable,Bastones clasicos - Sigilo,Bastones clasicos,Forma,9.75,"13 X 0,75 KG",13,...,+10%,-20%,-30%,+10%,+0%,0.0,63341.005,0.00,0.000,0.000
2,BR0003,Gajos de brocoli - sazonado - Caja de 13 packs...,Gajos de brocoli,Forma estable,Bastones clasicos - Sigilo,Bastones clasicos,Forma,9.75,"13 X 0,75 KG",13,...,"+10,00%",-10%,+10%,10,-20%,0.0,0.000,0.00,0.000,84527.940
3,BR0004,Bastones rectos de brocoli - crocante - Caja d...,Bastones rectos de brocoli,Estacional,Bastones clasicos - Sigilo,Bastones clasicos,Grueso,11.25,"9 X 1,5 KG",9,...,+10%,-20%,+10%,+10%,-20%,0.0,0.000,0.00,0.000,123630.325
4,BR0005,"13 bolsas de 0,75 kg | Espirales de brocoli si...",Espirales de brocoli,Forma estable,Bastones clasicos - Sigilo,Bastones clasicos,Forma,9.75,"13 X 0,75 KG",13,...,+10%,-20,-30,+10%,+10%,0.0,4248.160,0.00,0.000,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
458,BR0417,Mix crujiente de brocoli - clasico - Caja de 1...,Mix crujiente de brocoli,Forma estable,Bastones clasicos - Sigilo,Bastones clasicos,Forma,8.25,"11 X 0,75 KG",11,...,+ 10%,+10%,+10%,+10%,10%,0.0,0.000,1932.70,0.000,0.000
459,BR0418,"BonsaiGreen Mix crujiente de brocoli 11 x 0,75 kg",Mix crujiente de brocoli,Forma estable,Bastones clasicos - Sigilo,Bastones clasicos,Forma,8.25,"11 X 0,75 KG",11,...,+ 10%,+10%,+10%,+10%,10%,0.0,0.000,2759.40,0.000,0.000
460,BR0419,"5 bolsas de 2,5 kg | Bastones rectos de brocol...",Bastones rectos de brocoli,Estacional,Bastones clasicos - Reserva Privada,Bastones clasicos,Corte steak,12.50,"5 X 2,5 KG",5,...,+10%,+10%,+10%,+0%,+10%,0.0,0.000,0.00,25330.500,0.000
461,BR0420,"5 bolsas de 2,5 kg | Bastones rectos de brocol...",Bastones rectos de brocoli,Estacional,Bastones clasicos - Reserva Privada,Bastones clasicos,Medio,12.50,"5 X2,5 KG",5,...,-10%,-20%,+10%,-30%,+10%,0.0,11023.285,0.00,82639.375,0.000
462,BR0421,"5 bolsas de 2,5 kg | Bastones rectos de brocol...",Bastones rectos de brocoli,Estacional,Bastones clasicos - Reserva Privada,Bastones clasicos,Medio,12.50,"5 X 2,5 KG",5,...,+10%,-30%,-20%,-30%,-30%,0.0,0.000,0.00,66340.365,0.000

In [14]:
especificaciones_cajas['cantidad_cajas_total']

0      56.0
1      72.0
2      72.0
3      48.0
4      56.0
       ...
199    72.0
200    48.0
201    64.0
202    64.0
203    64.0
Name: cantidad_cajas_total, Length: 204, dtype: float64

In [15]:
catalogo_productos['cantidad_paquetes']

0       5
1      13
2      13
3       9
4      13
       ..
430    11
431    11
432     5
433     5
434     5
Name: cantidad_paquetes, Length: 435, dtype: int64

In [ ]:
mergeado = catalogo_productos.merge(
    especificaciones_cajas,
    on='caja_tipo_id',
    how='left'
)

In [46]:
especificaciones_cajas.columns

Index(['caja_tipo_id', 'caja_grosor_mm', 'caja_interior_largo',
       'caja_interior_ancho', 'caja_interior_alto', 'caja_exterior_largo',
       'caja_exterior_ancho', 'caja_exterior_alto', 'pallet_alto',
       'pallet_ancho', 'pallet_largo', 'cantidad_cajas_alto',
       'cantidad_cajas_largo', 'cantidad_cajas_ancho', 'cantidad_cajas_total',
       'utilizacion', 'caja_exterior_largo_calculado',
       'caja_exterior_ancho_calculado', 'caja_exterior_alto_calculado'],
      dtype='str')

In [47]:
operaciones_planta.columns

Index(['codigo_producto', 'volumen_producto_canal_servicios_comida',
       'volumen_producto_canal_minorista',
       'volumen_producto_canal_cadenas_corporativas',
       'volumen_producto_canal_otros', 'volumen_producto_total',
       'volumen_producto_planta_buenos_aires',
       'volumen_producto_planta_curitiba', 'volumen_producto_planta_santiago',
       'volumen_producto_planta_monterrey',
       'volumen_producto_planta_bakersfield',
       'cantidad_pallets_planta_buenos_aires',
       'cantidad_pallets_planta_curitiba', 'cantidad_pallets_planta_santiago',
       'cantidad_pallets_planta_monterrey',
       'cantidad_pallets_planta_bakersfield', 'cantidad_pallets_total',
       'costo_total_planta_buenos_aires', 'costo_total_planta_curitiba',
       'costo_total_planta_santiago', 'costo_total_planta_monterrey',
       'costo_total_planta_bakersfield', 'costo_pallets_planta_buenos_aires',
       'costo_pallets_planta_curitiba', 'costo_pallets_planta_santiago',
       'costo_pallets_planta_monterrey', 'costo_pallets_planta_bakersfield',
       'costo_pallets_total', 'costo_total',
       'volumen_producto_total_calculado', 'volumen_producto_total_calculado2',
       'cantidad_pallets_total_calculado', 'costo_pallets_total_calculado',
       'costo_total_calculado', 'costo_pallets_planta_buenos_aires_calculado',
       'costo_pallets_planta_curitiba_calculado',
       'costo_pallets_planta_santiago_calculado',
       'costo_pallets_planta_monterrey_calculado',
       'costo_pallets_planta_bakersfield_calculado'],
      dtype='str')

In [50]:
mergeado2.columns

Index(['codigo_producto', 'descripcion_producto', 'ingrediente_forma',
       'tipo_proyecto', 'subcategoria', 'categoria', 'tamaño_corte',
       'peso_neto_caja', 'tamaño_paquete', 'cantidad_paquetes',
       'peso_neto_paquete', 'caja_tipo_id', 'caja_grosor_mm',
       'caja_interior_largo', 'caja_interior_ancho', 'caja_interior_alto',
       'caja_exterior_largo', 'caja_exterior_ancho', 'caja_exterior_alto',
       'pallet_alto', 'pallet_ancho', 'pallet_largo', 'cantidad_cajas_alto',
       'cantidad_cajas_largo', 'cantidad_cajas_ancho', 'cantidad_cajas_total',
       'utilizacion', 'caja_exterior_largo_calculado',
       'caja_exterior_ancho_calculado', 'caja_exterior_alto_calculado',
       'cantidad_paquetes_pallet', 'volumen_producto_canal_servicios_comida',
       'volumen_producto_canal_minorista',
       'volumen_producto_canal_cadenas_corporativas',
       'volumen_producto_canal_otros', 'volumen_producto_total',
       'volumen_producto_planta_buenos_aires',
       'volumen_producto_planta_curitiba', 'volumen_producto_planta_santiago',
       'volumen_producto_planta_monterrey',
       'volumen_producto_planta_bakersfield',
       'cantidad_pallets_planta_buenos_aires',
       'cantidad_pallets_planta_curitiba', 'cantidad_pallets_planta_santiago',
       'cantidad_pallets_planta_monterrey',
       'cantidad_pallets_planta_bakersfield', 'cantidad_pallets_total',
       'costo_total_planta_buenos_aires', 'costo_total_planta_curitiba',
       'costo_total_planta_santiago', 'costo_total_planta_monterrey',
       'costo_total_planta_bakersfield', 'costo_pallets_planta_buenos_aires',
       'costo_pallets_planta_curitiba', 'costo_pallets_planta_santiago',
       'costo_pallets_planta_monterrey', 'costo_pallets_planta_bakersfield',
       'costo_pallets_total', 'costo_total',
       'volumen_producto_total_calculado', 'volumen_producto_total_calculado2',
       'cantidad_pallets_total_calculado', 'costo_pallets_total_calculado',
       'costo_total_calculado', 'costo_pallets_planta_buenos_aires_calculado',
       'costo_pallets_planta_curitiba_calculado',
       'costo_pallets_planta_santiago_calculado',
       'costo_pallets_planta_monterrey_calculado',
       'costo_pallets_planta_bakersfield_calculado', 'vol_calculado'],
      dtype='str')

In [53]:
mergeado2 = mergeado.merge(operaciones_planta,
                           on='codigo_producto'
                           )

cant_pallets_plantas = [c for c in mergeado2.columns if c.startswith('cantidad_pallets_planta_')]

mergeado2['vol_calculado'] = mergeado2[cant_pallets_plantas].mul(
    mergeado2['cantidad_cajas_total'], axis=0
).sum(axis=1)   
verificar_correctitud(mergeado2, 'volumen_producto_total', 'vol_calculado')

448 FILAS NO coinciden

     volumen_producto_total  vol_calculado  coincide
0                   1546613      1546680.0     False
1                    139211       139248.0     False
2                    172506       172560.0     False
3                    271715       271768.0     False
4                      7586         7632.0     False
..                      ...            ...       ...
458                    2761         2800.0     False
459                    3942         3976.0     False
460                   43300        43344.0     False
461                  205852       205888.0     False
462                  145803       145824.0     False

[448 rows x 3 columns]

In [52]:
condicion = mergeado2['vol_calculado'] <= mergeado2['volumen_producto_total'] + mergeado2['cantidad_cajas_total']
mergeado2[~condicion][['volumen_producto_total','cantidad_cajas_total','vol_calculado']]

     volumen_producto_total  cantidad_cajas_total  vol_calculado
0                   1546613                  40.0      1546680.0
8                     18019                  72.0        18216.0
19                    91699                  64.0        91776.0
24                   139891                  72.0       139968.0
47                      222                  56.0          336.0
..                      ...                   ...            ...
450                     220                  56.0          336.0
453                    2347                  56.0         2520.0
455                     225                  72.0          432.0
456                     226                  48.0          336.0
457                     214                  72.0          432.0

[106 rows x 3 columns]

In [33]:
mergeado2[~condicion]['vol_calculado'] - mergeado2[~condicion]['volumen_producto_total']

0       67.0
8      197.0
19      77.0
24      77.0
47     114.0
       ...
450    116.0
453    173.0
455    207.0
456    110.0
457    218.0
Length: 106, dtype: float64

In [34]:
especificaciones_cajas

,caja_tipo_id,caja_grosor_mm,caja_interior_largo,caja_interior_ancho,caja_interior_alto,caja_exterior_largo,caja_exterior_ancho,caja_exterior_alto,pallet_alto,pallet_ancho,pallet_largo,cantidad_cajas_alto,cantidad_cajas_largo,cantidad_cajas_ancho,cantidad_cajas_total,utilizacion,caja_exterior_largo_calculado,caja_exterior_ancho_calculado,caja_exterior_alto_calculado
0,016d196c89dcfcb306b853a776a879b9,4.8,383.0,248.0,224.0,392.6,257.6,233.6,1800,800,1200,7.0,2.0,4.0,56.0,0.765620,392.6,257.6,233.6
1,01a2a319402ed2155292c04d8748e16f,4.7,380.0,282.0,185.0,389.4,291.4,194.4,1800,800,1200,9.0,2.0,4.0,72.0,0.919116,389.4,291.4,194.4
2,026560e43f3fc6afe0ce89d7ddf61626,4.1,390.0,290.0,184.0,398.2,298.2,192.2,1800,800,1200,9.0,2.0,4.0,72.0,0.950935,398.2,298.2,192.2
3,02d7c6680102bd11e067c00c9b71ab9c,4.8,383.0,248.0,268.0,392.6,257.6,277.6,1800,800,1200,6.0,2.0,4.0,48.0,0.779854,392.6,257.6,277.6
4,0378f85c226113f4ac40fd360217bb8a,4.1,390.0,289.0,224.0,398.2,297.2,232.2,1800,800,1200,7.0,2.0,4.0,56.0,0.890546,398.2,297.2,232.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,f609bd5b4ffc901bae0837e2befee31d,4.7,380.0,282.0,175.0,389.4,291.4,184.4,1800,800,1200,9.0,2.0,4.0,72.0,0.871837,389.4,291.4,184.4
200,fc5516122a48681b6a5d3d70768ee02a,4.1,390.0,255.0,275.0,398.2,263.2,283.2,1800,800,1200,6.0,2.0,4.0,48.0,0.824476,398.2,263.2,283.2
201,fcc3ee3ebc86c553e5f951274d02868e,4.1,390.0,289.0,214.0,398.2,297.2,222.2,1800,800,1200,8.0,2.0,4.0,64.0,0.973936,398.2,297.2,222.2
202,fce36b1b860f566c05d3e06484e6f4e2,4.8,388.0,287.0,194.0,397.6,296.6,203.6,1800,800,1200,8.0,2.0,4.0,64.0,0.889266,397.6,296.6,203.6
203,fdfc2140b8ceabc8da48b6c2886fe22d,4.1,390.0,255.0,199.0,398.2,263.2,207.2,1800,800,1200,8.0,2.0,4.0,64.0,0.804291,398.2,263.2,207.2

In [38]:
c = (1200 // especificaciones_cajas['caja_exterior_ancho_calculado']).astype(int) # limitado por altura

especificaciones_cajas[~np.isclose(especificaciones_cajas['cantidad_cajas_ancho'],c)]

Empty DataFrame
Columns: [caja_tipo_id, caja_grosor_mm, caja_interior_largo, caja_interior_ancho, caja_interior_alto, caja_exterior_largo, caja_exterior_ancho, caja_exterior_alto, pallet_alto, pallet_ancho, pallet_largo, cantidad_cajas_alto, cantidad_cajas_largo, cantidad_cajas_ancho, cantidad_cajas_total, utilizacion, caja_exterior_largo_calculado, caja_exterior_ancho_calculado, caja_exterior_alto_calculado]
Index: []