#### **REDIMENSIONAMIENTO DE LAS CAJAS**

In [141]:
import pandas as pd 
import matplotlib.pyplot as plt
from importlib import reload

import Clases.caja as caja_module
reload(caja_module)
from Clases.caja import Caja

import Clases.producto as producto_module
reload(producto_module)
from Clases.producto import Producto

especificaciones_cajas = pd.read_csv("Datos-finales/especificaciones_cajas.csv")
procurement_cajas = pd.read_csv("Datos-finales/procurement_cajas.csv")

Importamos en una lista los tipos de cajas del dataset.

In [142]:
caja_compras_merge = especificaciones_cajas.merge(procurement_cajas,
                                                  on="caja_tipo_id")

cajas = [
    Caja(
        caja_id = row["caja_tipo_id"],
        dim_interior_ancho = row["caja_interior_ancho"],
        dim_interior_largo = row["caja_interior_largo"],
        dim_interior_alto = row["caja_interior_alto"]
    )
    for _, row in caja_compras_merge.iterrows()
]

#### **Redimensionamiento con grosor = 5mm**

Para encontrar una cantidad óptima de cajas que entran en un pallet, necesitamos definir un redimensionamiento óptimo para las dimensiones internas de las cajas.

Siguiendo el enunciado, sólo podemos redimensionar un ±10% de las dimensiones internas originales.

In [143]:
for caja in cajas:
    caja.elegir_grosor(grosor_mm=5)
    
mejor_opcion_por_caja_5mm = {}
combinaciones_ordenadas_por_caja_5mm = {}

for caja in cajas:
    mejor_opcion, combinaciones_ordenadas = caja.buscar_redimensionamiento_optimo()
    mejor_opcion_por_caja_5mm[caja] = mejor_opcion
    combinaciones_ordenadas_por_caja_5mm[caja] = combinaciones_ordenadas

Veamos en un dataframe las mejores combinaciones de redimensionamiento por cada tipo de caja.

In [144]:
datos = []

for caja, mejor in mejor_opcion_por_caja_5mm.items():
    datos.append({
        'caja_id': caja.caja_id,
        'alto': mejor[0],
        'ancho': mejor[1],
        'largo': mejor[2],
        'utilizacion_pallet': mejor[3]
    })

df_mejor_opcion_5mm = pd.DataFrame(datos)
df_mejor_opcion_5mm

                              caja_id   alto  ancho  largo  utilizacion_pallet
0    02cf77de65b70dd77905e2e33d78478f  320.1  266.4  355.5            0.771946
1    082c1cdb42b1abd201403ca33ca11ef0  189.0  223.2  383.0            0.949889
2    0835ff365412a67b720a19713ec250f3  278.0  286.0  386.0            0.937728
3    0b72571a5bb7429ce7de424547e8d27d  156.6  286.0  386.0            0.904083
4    10c5f9edbe2c87186bcdeb991fe8d902  205.2  226.8  380.0            0.920100
..                                ...    ...    ...    ...                 ...
199  fa8da38322149b23e14a120e71d38975  211.5  229.5  353.7            0.893241
200  fc6931875b8384c7bacd18bb4699795f  240.9  229.5  353.7            0.885327
201  fe503fe59c48da80878a0b8f7ad58dcb  183.6  223.2  383.0            0.924113
202  fe7802fb3f92b710413a4de88233a3f7  156.6  288.0  388.0            0.914788
203  fea00d6f87d3f80808e9e8d1b501120a  165.6  266.4  355.5            0.821289

[204 rows x 5 columns]

Por otro lado, exportamos en csv todas las combinaciones posibles de redimensionamiento por caja.

In [145]:
data = []

for caja, combinaciones in combinaciones_ordenadas_por_caja_5mm.items():
    for combinacion in combinaciones:
        data.append({
            'caja_id': caja.caja_id,
            'alto': combinacion['alto'],
            'ancho': combinacion['ancho'],
            'largo': combinacion['largo'],
            'utilizacion': combinacion['utilizacion_pallet']
        })

df_todas_combinaciones_5mm = pd.DataFrame(data)
df_todas_combinaciones_5mm.to_csv('Redimensionamientos/redimensionamientos_5mm.csv', index=False)

#### **Redimensionamiento con grosor = 4.5mm**

Repetimos lo anterior con un grosor de 4.5mm.

In [146]:
for caja in cajas:
    caja.elegir_grosor(grosor_mm=4.5)
    
mejor_opcion_por_caja_4p5mm = {}
combinaciones_ordenadas_por_caja_4p5mm = {}

for caja in cajas:
    mejor_opcion, combinaciones_ordenadas = caja.buscar_redimensionamiento_optimo()
    mejor_opcion_por_caja_4p5mm[caja] = mejor_opcion
    combinaciones_ordenadas_por_caja_4p5mm[caja] = combinaciones_ordenadas

In [147]:
datos = []

for caja, mejor in mejor_opcion_por_caja_4p5mm.items():
    datos.append({
        'caja_id': caja.caja_id,
        'alto': mejor[0],
        'ancho': mejor[1],
        'largo': mejor[2],
        'utilizacion_pallet': mejor[3]
    })

df_mejor_opcion_4p5mm = pd.DataFrame(datos)
df_mejor_opcion_4p5mm

                              caja_id   alto  ancho  largo  utilizacion_pallet
0    02cf77de65b70dd77905e2e33d78478f  291.0  266.4  355.5            0.836527
1    082c1cdb42b1abd201403ca33ca11ef0  170.1  223.2  383.0            0.943409
2    0835ff365412a67b720a19713ec250f3  278.0  286.0  386.0            0.928963
3    0b72571a5bb7429ce7de424547e8d27d  156.6  286.0  386.0            0.893358
4    10c5f9edbe2c87186bcdeb991fe8d902  205.2  226.8  380.0            0.909618
..                                ...    ...    ...    ...                 ...
199  fa8da38322149b23e14a120e71d38975  211.5  229.5  353.7            0.883061
200  fc6931875b8384c7bacd18bb4699795f  240.9  229.5  353.7            0.875702
201  fe503fe59c48da80878a0b8f7ad58dcb  183.6  223.2  383.0            0.913068
202  fe7802fb3f92b710413a4de88233a3f7  156.6  288.0  388.0            0.903969
203  fea00d6f87d3f80808e9e8d1b501120a  165.6  266.4  355.5            0.811432

[204 rows x 5 columns]

In [148]:
data = []

for caja, combinaciones in combinaciones_ordenadas_por_caja_4p5mm.items():
    for combinacion in combinaciones:
        data.append({
            'caja_id': caja.caja_id,
            'alto': combinacion['alto'],
            'ancho': combinacion['ancho'],
            'largo': combinacion['largo'],
            'utilizacion': combinacion['utilizacion_pallet']
        })

df_todas_combinaciones_4p5mm = pd.DataFrame(data)
df_todas_combinaciones_4p5mm.to_csv('Redimensionamientos/redimensionamientos_4.5mm.csv', index=False)

#### **Redimensionamiento con grosor = 3mm**

Por último, redimensionemos los tipos de cajas con un grosor de 3mm.

In [149]:
for caja in cajas:
    caja.elegir_grosor(grosor_mm=3)
    
mejor_opcion_por_caja_3mm = {}
combinaciones_ordenadas_por_caja_3mm = {}

for caja in cajas:
    mejor_opcion, combinaciones_ordenadas = caja.buscar_redimensionamiento_optimo()
    mejor_opcion_por_caja_3mm[caja] = mejor_opcion
    combinaciones_ordenadas_por_caja_3mm[caja] = combinaciones_ordenadas

In [150]:
datos = []

for caja, mejor in mejor_opcion_por_caja_3mm.items():
    datos.append({
        'caja_id': caja.caja_id,
        'alto': mejor[0],
        'ancho': mejor[1],
        'largo': mejor[2],
        'utilizacion_pallet': mejor[3]
    })

df_mejor_opcion_3mm = pd.DataFrame(datos)
df_mejor_opcion_3mm

                              caja_id   alto  ancho  largo  utilizacion_pallet
0    02cf77de65b70dd77905e2e33d78478f  291.0  266.4  355.5            0.812399
1    082c1cdb42b1abd201403ca33ca11ef0  170.1  223.2  383.0            0.908615
2    0835ff365412a67b720a19713ec250f3  250.2  286.0  386.0            0.950369
3    0b72571a5bb7429ce7de424547e8d27d  174.0  286.0  386.0            0.953867
4    10c5f9edbe2c87186bcdeb991fe8d902  250.8  226.8  380.0            0.934802
..                                ...    ...    ...    ...                 ...
199  fa8da38322149b23e14a120e71d38975  211.5  229.5  393.0            0.946170
200  fc6931875b8384c7bacd18bb4699795f  219.0  229.5  393.0            0.978797
201  fe503fe59c48da80878a0b8f7ad58dcb  183.6  223.2  383.0            0.880443
202  fe7802fb3f92b710413a4de88233a3f7  174.0  288.0  388.0            0.965300
203  fea00d6f87d3f80808e9e8d1b501120a  165.6  266.4  355.5            0.782310

[204 rows x 5 columns]

In [151]:
data = []

for caja, combinaciones in combinaciones_ordenadas_por_caja_3mm.items():
    for combinacion in combinaciones:
        data.append({
            'caja_id': caja.caja_id,
            'alto': combinacion['alto'],
            'ancho': combinacion['ancho'],
            'largo': combinacion['largo'],
            'utilizacion': combinacion['utilizacion_pallet']
        })

df_todas_combinaciones_3mm = pd.DataFrame(data)
df_todas_combinaciones_3mm.to_csv('Redimensionamientos/redimensionamientos_3mm.csv', index=False)