#### **OPTIMALIDAD DE LA SOLUCION - ALGORITMOS GREEDY**

In [28]:
import pandas as pd 
from importlib import reload
import random

import Clases.asignacion as asignacion_module
reload(asignacion_module)
from Clases.asignacion import Asignacion

import Clases.caja as caja_module
reload(caja_module)
from Clases.caja import Caja

import Clases.producto as producto_module
reload(producto_module)
from Clases.producto import Producto

import Clases.solucion as solucion_module
reload(solucion_module)
from Clases.solucion import Solucion

import Algoritmos.greedy as greedy_module
reload(greedy_module)
from Algoritmos.greedy import solucion_greedy

catalogo_productos = pd.read_csv("Datos-finales/catalogo_productos.csv")
operaciones_planta = pd.read_csv("Datos-finales/operaciones_planta.csv")

cajas_nuevas = pd.read_csv("4r.cajas_nuevas.csv")
factibilidad = pd.read_csv("Factibilidad/factibilidad_4.5mm.csv")

In [29]:
grosor = 5

Empecemos guardando los productos y tipos de cajas en listas en el estado actual, para cargarlos luego a las soluciones. Almacenamos también las cajas asignables a cada producto en un diccionario.

In [30]:
def guardar_cajas_y_productos(grosor=grosor):
    
    cajas = {
        row["caja_tipo_id"]: Caja(
            caja_id=row["caja_tipo_id"],
            dim_interior_ancho=row["caja_interior_ancho"],
            dim_interior_largo=row["caja_interior_largo"],
            dim_interior_alto=row["caja_interior_alto"]
        )
        for _, row in cajas_nuevas.iterrows()
    }

    prod_op_merge = catalogo_productos.merge(operaciones_planta, on="codigo_producto")
    productos = {
        row["codigo_producto"]: Producto(
            codigo_producto = row['codigo_producto'],
            cantidad_paquetes = row['cantidad_paquetes'],
            peso_paquete = row['peso_neto_paquete'],
            demanda_buenos_aires = row['volumen_producto_planta_buenos_aires'],
            demanda_curitiba = row['volumen_producto_planta_curitiba'],
            demanda_santiago = row['volumen_producto_planta_santiago'],
            demanda_monterrey = row['volumen_producto_planta_monterrey'],
            demanda_bakersfield = row['volumen_producto_planta_bakersfield'],
            dim_producto_ancho = row['dim_producto_ancho'], 
            dim_producto_largo = row['dim_producto_largo'],
            dim_producto_alto = row['dim_producto_alto']
        )
        for _, row in prod_op_merge.iterrows()
    }
    
    cajas_asignables_por_producto = {}

    for codigo, group in factibilidad.groupby('codigo_producto'):
        # Obtener IDs de los tipos de cajas
        cajas_ids_unicos = list(group['caja_tipo_id'].unique())
        
        cajas_producto = []
        for caja_id in cajas_ids_unicos:
            cajas_producto.append(caja_id)
            
        cajas_asignables_por_producto[codigo] = cajas_producto
                
    # Elegir grosor
    for caja_id, caja in cajas.items():
        caja.elegir_grosor(grosor_mm=grosor)
        
    return cajas, productos, cajas_asignables_por_producto

#### **Greedy 1: Ordenamiento de productos según la cantidad de cajas asignables**

La idea ahora sería comparar las soluciones determinadas a partir de cada criterio Greedy, ordenando antes los productos según la cantidad de cajas asignables, de menor de mayor.

De esta manera, el algoritmo se ejecutaría gradualmente abriéndose en cada vez más posibilidades de cajas asignables.

In [31]:
def ordenar_por_cajas_asignables(asignaciones_por_producto):
    '''
    Ordenamos los productos según la cantidad de cajas asignables de menor a mayor
    '''
    productos_conteo = []

    for codigo_producto, cajas_asignables in asignaciones_por_producto.items():
        cantidad_cajas = len(cajas_asignables)  # Número de cajas asignables para este producto    
        productos_conteo.append({
            'codigo_producto': codigo_producto,
            'cantidad_cajas_asignables': cantidad_cajas
        })

    # Ordenar de menor a mayor cantidad de cajas
    productos_ordenados = sorted(
        productos_conteo,
        key=lambda x: x['cantidad_cajas_asignables'],
        reverse=False
    )

    lista_productos_ordenados = [item['codigo_producto'] for item in productos_ordenados]
    return lista_productos_ordenados

Guardaremos todas las soluciones greedy en una lista, para facilitar la comparación posterior.

In [32]:
soluciones_greedy = []

In [33]:
cajas, productos, asignaciones_por_producto = guardar_cajas_y_productos()
lista_productos_ordenados = ordenar_por_cajas_asignables(asignaciones_por_producto)

solucion_greedy1 = solucion_greedy(cajas, productos, lista_productos_ordenados, asignaciones_por_producto, 
                                   criterio_greedy="minimizar_costo_total",
                                   titulo_solucion="Greedy minimizando costo total | Ordenamiento según #cajas asignables",
                                   grosor=grosor)
soluciones_greedy.append(solucion_greedy1)
solucion_greedy1.resumen_general()

Situación original
--------------------------------------------------
Número de tipos de cajas distintos: 204
Costo packaging: 30166293.939999998
Costo flete: 179068800
Costo total: 209235093.94
Utilización de pallet promedio: 0.8320794116391749
Utilización de caja promedio: 1.0

Situación nueva
--------------------------------------------------
Grosor elegido: 5mm
Criterio elegido: Greedy minimizando costo total | Ordenamiento según #cajas asignables
Número de tipos de cajas distintos: 121
Costo packaging: 32415602.44999999
Costo flete: 167864400
Costo total: 200280002.45
Utilización de pallet promedio: 0.9173892694533933
Utilización de caja promedio: 0.9910799601074044
Ahorro costo total: 4.27992%

In [34]:
solucion_greedy1.resumen_por_asignacion()

,codigo_producto,volumen_producto_total,demanda_total,caja_id,utilizacion_pallet,utilizacion_caja,descuento_buenos_aires,descuento_curitiba,descuento_santiago,descuento_monterrey,descuento_bakersfield,costo_packaging,cant_pallets,costo_flete,costo_total
0,BR0001,1546613,1546613,CAJ0358186,0.866667,0.979324,0.1,-0.3,-0.2,-0.1,-0.2,772060.94,38667,5800050,6572110.94
1,BR0002,139211,139211,CAJ0291786,0.933333,0.995487,-0.3,-0.2,-0.3,0.1,-0.2,77958.16,2901,435150,513108.16
2,BR0003,172506,172506,CAJ0072296,0.955421,1.000000,0.1,0.1,0.1,0.1,-0.2,96603.36,2157,323550,420153.36
3,BR0004,271715,271715,CAJ0212936,0.941111,0.998128,0.1,-0.3,0.1,-0.1,-0.3,133140.35,4853,727950,861090.35
4,BR0005,7586,7586,CAJ0266886,0.893333,0.957175,-0.1,-0.2,-0.1,0.0,-0.2,4248.16,159,23850,28098.16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
422,BR0417,2761,2761,CAJ0175035,0.917935,0.998817,0.1,0.1,0.1,0.1,0.1,2125.97,44,6600,8725.97
423,BR0418,3942,3942,CAJ0175035,0.917935,0.998817,0.1,0.1,0.1,0.1,0.1,3035.34,62,9300,12335.34
424,BR0419,43300,43300,CAJ0105050,0.945250,0.998695,0.1,0.1,0.1,0.0,0.1,30310.00,602,90300,120610.00
425,BR0420,205852,205852,CAJ0125436,0.953333,0.999622,-0.3,-0.3,0.0,-0.3,0.1,100867.48,2860,429000,529867.48
426,BR0421,145803,145803,CAJ0166935,0.927487,0.998207,-0.2,-0.3,-0.3,-0.3,-0.3,71443.47,2279,341850,413293.47

In [ ]:
cajas, productos, asignaciones_por_producto = guardar_cajas_y_productos()
lista_productos_ordenados = ordenar_por_cajas_asignables(asignaciones_por_producto)

solucion_greedy2 = solucion_greedy(cajas, lista_productos_ordenados, asignaciones_por_producto, 
                                   productos=productos, grosor=grosor,
                                   criterio_greedy="minimizar_costo_flete",
                                   titulo_solucion="Greedy minimizando costo flete | Ordenamiento según #cajas asignables")
soluciones_greedy.append(solucion_greedy2)
solucion_greedy2.resumen_general()

Situación original
--------------------------------------------------
Número de tipos de cajas distintos: 204
Costo packaging: 30166293.939999998
Costo flete: 179068800
Costo total: 209235093.94
Utilización de pallet promedio: 0.8320794116391749
Utilización de caja promedio: 1.0

Situación nueva
--------------------------------------------------
Grosor elegido: 4.5mm
Criterio elegido: Greedy minimizando costo flete | Ordenamiento según #cajas asignables
Número de tipos de cajas distintos: 167
Costo packaging: 31046709.915000003
Costo flete: 166867200
Costo total: 197913909.915
Utilización de pallet promedio: 0.9073660470205767
Utilización de caja promedio: 0.9980452559351544
Ahorro costo total: 5.41075%

In [ ]:
cajas, productos, asignaciones_por_producto = guardar_cajas_y_productos()
lista_productos_ordenados = ordenar_por_cajas_asignables(asignaciones_por_producto)

solucion_greedy3 = solucion_greedy(cajas, lista_productos_ordenados, asignaciones_por_producto,
                                   productos=productos, grosor=grosor,
                                   criterio_greedy="maximizar_utilizacion_pallet",
                                   titulo_solucion="Greedy maximizando utilizacion pallet | Ordenamiento según #cajas asignables")
soluciones_greedy.append(solucion_greedy3)
solucion_greedy3.resumen_general()

Situación original
--------------------------------------------------
Número de tipos de cajas distintos: 204
Costo packaging: 30166293.939999998
Costo flete: 179068800
Costo total: 209235093.94
Utilización de pallet promedio: 0.8320794116391749
Utilización de caja promedio: 1.0

Situación nueva
--------------------------------------------------
Grosor elegido: 4.5mm
Criterio elegido: Greedy maximizando utilizacion pallet | Ordenamiento según #cajas asignables
Número de tipos de cajas distintos: 75
Costo packaging: 29861720.52500001
Costo flete: 167446950
Costo total: 197308670.525
Utilización de pallet promedio: 0.9626579094912282
Utilización de caja promedio: 0.9347970108001431
Ahorro costo total: 5.70001%

In [ ]:
cajas, productos, asignaciones_por_producto = guardar_cajas_y_productos()
lista_productos_ordenados = ordenar_por_cajas_asignables(asignaciones_por_producto)

solucion_greedy4 = solucion_greedy(cajas, lista_productos_ordenados, asignaciones_por_producto, 
                                   productos=productos, grosor=grosor,
                                   criterio_greedy="maximizar_volumen_tipo",
                                   titulo_solucion="Greedy maximizando volumen caja | Ordenamiento según #cajas asignables")
soluciones_greedy.append(solucion_greedy4)
solucion_greedy4.resumen_general()

Situación original
--------------------------------------------------
Número de tipos de cajas distintos: 204
Costo packaging: 30166293.939999998
Costo flete: 179068800
Costo total: 209235093.94
Utilización de pallet promedio: 0.8320794116391749
Utilización de caja promedio: 1.0

Situación nueva
--------------------------------------------------
Grosor elegido: 4.5mm
Criterio elegido: Greedy maximizando volumen caja | Ordenamiento según #cajas asignables
Número de tipos de cajas distintos: 51
Costo packaging: 29709012.77500002
Costo flete: 172219500
Costo total: 201928512.77500004
Utilización de pallet promedio: 0.9054256470391231
Utilización de caja promedio: 0.9701655515037144
Ahorro costo total: 3.49204%

#### **Greedy 2: Ordenamiento de productos según su demanda total**

Repetiremos todos los criterios Greedy ordenando ahora los productos según su demanda total, de mayor a menor, para luego comparar con los resultados obtenidos anteriormente.

De esta manera, aceleraríamos la aplicación de descuentos para reducir el costo packaging lo antes posible.

In [ ]:
def ordenar_por_demanda_total(productos):
    '''
    Ordenamos los productos según la demanda total de mayor a menor
    '''
    productos_ordenados = sorted(
        productos.values(),
        key=lambda p: p.demanda_total(),
        reverse=True
    )
    return [p.codigo_producto for p in productos_ordenados]

In [ ]:
cajas, productos, asignaciones_por_producto = guardar_cajas_y_productos()
lista_productos_ordenados = ordenar_por_demanda_total(productos)

solucion_greedy5 = solucion_greedy(cajas, lista_productos_ordenados, asignaciones_por_producto, 
                                   productos=productos, grosor=grosor,
                                   criterio_greedy="minimizar_costo_total",
                                   titulo_solucion="Greedy minimizando costo total | Ordenamiento según demanda total")
soluciones_greedy.append(solucion_greedy5)
solucion_greedy5.resumen_general()

Situación original
--------------------------------------------------
Número de tipos de cajas distintos: 204
Costo packaging: 30166293.939999998
Costo flete: 179068800
Costo total: 209235093.94
Utilización de pallet promedio: 0.8320794116391749
Utilización de caja promedio: 1.0

Situación nueva
--------------------------------------------------
Grosor elegido: 4.5mm
Criterio elegido: Greedy minimizando costo total | Ordenamiento según demanda total
Número de tipos de cajas distintos: 103
Costo packaging: 30035343.065000016
Costo flete: 166875150
Costo total: 196910493.06500003
Utilización de pallet promedio: 0.9140200706387047
Utilización de caja promedio: 0.9905407457584094
Ahorro costo total: 5.89031%

In [ ]:
cajas, productos, asignaciones_por_producto = guardar_cajas_y_productos()
lista_productos_ordenados = ordenar_por_demanda_total(productos)

solucion_greedy6 = solucion_greedy(cajas, lista_productos_ordenados, asignaciones_por_producto, 
                                   productos=productos, grosor=grosor,
                                   criterio_greedy="minimizar_costo_flete",
                                   titulo_solucion="Greedy minimizando costo flete | Ordenamiento según demanda total")
soluciones_greedy.append(solucion_greedy6)
solucion_greedy6.resumen_general()

Situación original
--------------------------------------------------
Número de tipos de cajas distintos: 204
Costo packaging: 30166293.939999998
Costo flete: 179068800
Costo total: 209235093.94
Utilización de pallet promedio: 0.8320794116391749
Utilización de caja promedio: 1.0

Situación nueva
--------------------------------------------------
Grosor elegido: 4.5mm
Criterio elegido: Greedy minimizando costo flete | Ordenamiento según demanda total
Número de tipos de cajas distintos: 167
Costo packaging: 31046709.915000018
Costo flete: 166867200
Costo total: 197913909.91500002
Utilización de pallet promedio: 0.907366047020576
Utilización de caja promedio: 0.9980452559351541
Ahorro costo total: 5.41075%

In [ ]:
cajas, productos, asignaciones_por_producto = guardar_cajas_y_productos()
lista_productos_ordenados = ordenar_por_demanda_total(productos)

solucion_greedy7 = solucion_greedy(cajas, lista_productos_ordenados, asignaciones_por_producto, 
                                   productos=productos, grosor=grosor,
                                   criterio_greedy="maximizar_utilizacion_pallet",
                                   titulo_solucion="Greedy maximizando utilizacion pallet | Ordenamiento según demanda total")
soluciones_greedy.append(solucion_greedy7)
solucion_greedy7.resumen_general()

Situación original
--------------------------------------------------
Número de tipos de cajas distintos: 204
Costo packaging: 30166293.939999998
Costo flete: 179068800
Costo total: 209235093.94
Utilización de pallet promedio: 0.8320794116391749
Utilización de caja promedio: 1.0

Situación nueva
--------------------------------------------------
Grosor elegido: 4.5mm
Criterio elegido: Greedy maximizando utilizacion pallet | Ordenamiento según demanda total
Número de tipos de cajas distintos: 75
Costo packaging: 29861720.525
Costo flete: 167446950
Costo total: 197308670.525
Utilización de pallet promedio: 0.9626579094912281
Utilización de caja promedio: 0.9347970108001427
Ahorro costo total: 5.70001%

In [ ]:
cajas, productos, asignaciones_por_producto = guardar_cajas_y_productos()
lista_productos_ordenados = ordenar_por_demanda_total(productos)

solucion_greedy8 = solucion_greedy(cajas, lista_productos_ordenados, asignaciones_por_producto, 
                                   productos=productos, grosor=grosor,
                                   criterio_greedy="maximizar_volumen_tipo",
                                   titulo_solucion="Greedy maximizando volumen caja | Ordenamiento según demanda total")
soluciones_greedy.append(solucion_greedy8)
solucion_greedy8.resumen_general()

Situación original
--------------------------------------------------
Número de tipos de cajas distintos: 204
Costo packaging: 30166293.939999998
Costo flete: 179068800
Costo total: 209235093.94
Utilización de pallet promedio: 0.8320794116391749
Utilización de caja promedio: 1.0

Situación nueva
--------------------------------------------------
Grosor elegido: 4.5mm
Criterio elegido: Greedy maximizando volumen caja | Ordenamiento según demanda total
Número de tipos de cajas distintos: 57
Costo packaging: 29480241.569999997
Costo flete: 172333050
Costo total: 201813291.57
Utilización de pallet promedio: 0.9028180970594861
Utilización de caja promedio: 0.9710458612313503
Ahorro costo total: 3.54711%

#### **Greedy 3: Ordenamiento de productos de forma aleatoria**

Ordenemos los productos de forma aleatoria, fijando una semilla para la reproducibilidad, y comparemos los resultados con los anteriores casos.

In [ ]:
def ordenar_aleatorio(productos, seed):
    random.seed(seed)
    lista_productos = list(productos.values())
    random.shuffle(lista_productos)
    return [p.codigo_producto for p in lista_productos]

In [ ]:
cajas, productos, asignaciones_por_producto = guardar_cajas_y_productos()
lista_productos_ordenados = ordenar_aleatorio(productos, seed=2708)

solucion_greedy9 = solucion_greedy(cajas, lista_productos_ordenados, asignaciones_por_producto, 
                                   productos=productos, grosor=grosor,
                                   criterio_greedy="minimizar_costo_total",
                                   titulo_solucion="Greedy minimizando costo total | Ordenamiento aleatorio")
soluciones_greedy.append(solucion_greedy9)
solucion_greedy9.resumen_general()

Situación original
--------------------------------------------------
Número de tipos de cajas distintos: 204
Costo packaging: 30166293.939999998
Costo flete: 179068800
Costo total: 209235093.94
Utilización de pallet promedio: 0.8320794116391749
Utilización de caja promedio: 1.0

Situación nueva
--------------------------------------------------
Grosor elegido: 4.5mm
Criterio elegido: Greedy minimizando costo total | Ordenamiento aleatorio
Número de tipos de cajas distintos: 116
Costo packaging: 30087185.634999998
Costo flete: 166872900
Costo total: 196960085.635
Utilización de pallet promedio: 0.9165335536492827
Utilización de caja promedio: 0.9878599761350656
Ahorro costo total: 5.86661%

In [ ]:
cajas, productos, asignaciones_por_producto = guardar_cajas_y_productos()
lista_productos_ordenados = ordenar_aleatorio(productos, seed=2708)

solucion_greedy10 = solucion_greedy(cajas, lista_productos_ordenados, asignaciones_por_producto, 
                                    productos=productos, grosor=grosor,
                                    criterio_greedy="minimizar_costo_flete",
                                    titulo_solucion="Greedy minimizando costo flete | Ordenamiento aleatorio")
soluciones_greedy.append(solucion_greedy10)
solucion_greedy10.resumen_general()

Situación original
--------------------------------------------------
Número de tipos de cajas distintos: 204
Costo packaging: 30166293.939999998
Costo flete: 179068800
Costo total: 209235093.94
Utilización de pallet promedio: 0.8320794116391749
Utilización de caja promedio: 1.0

Situación nueva
--------------------------------------------------
Grosor elegido: 4.5mm
Criterio elegido: Greedy minimizando costo flete | Ordenamiento aleatorio
Número de tipos de cajas distintos: 167
Costo packaging: 31046709.915000018
Costo flete: 166867200
Costo total: 197913909.91500002
Utilización de pallet promedio: 0.9073660470205768
Utilización de caja promedio: 0.998045255935154
Ahorro costo total: 5.41075%

In [ ]:
cajas, productos, asignaciones_por_producto = guardar_cajas_y_productos()
lista_productos_ordenados = ordenar_aleatorio(productos, seed=2708)

solucion_greedy11 = solucion_greedy(cajas, lista_productos_ordenados, asignaciones_por_producto,
                                    productos=productos, grosor=grosor, 
                                    criterio_greedy="maximizar_utilizacion_pallet",
                                    titulo_solucion="Greedy maximizando utilizacion pallet | Ordenamiento aleatorio")
soluciones_greedy.append(solucion_greedy11)
solucion_greedy11.resumen_general()

Situación original
--------------------------------------------------
Número de tipos de cajas distintos: 204
Costo packaging: 30166293.939999998
Costo flete: 179068800
Costo total: 209235093.94
Utilización de pallet promedio: 0.8320794116391749
Utilización de caja promedio: 1.0

Situación nueva
--------------------------------------------------
Grosor elegido: 4.5mm
Criterio elegido: Greedy maximizando utilizacion pallet | Ordenamiento aleatorio
Número de tipos de cajas distintos: 75
Costo packaging: 29861720.524999995
Costo flete: 167446950
Costo total: 197308670.525
Utilización de pallet promedio: 0.9626579094912281
Utilización de caja promedio: 0.934797010800142
Ahorro costo total: 5.70001%

In [ ]:
cajas, productos, asignaciones_por_producto = guardar_cajas_y_productos()
lista_productos_ordenados = ordenar_aleatorio(productos, seed=2708)

solucion_greedy12 = solucion_greedy(cajas, lista_productos_ordenados, asignaciones_por_producto, 
                                    productos=productos, grosor=grosor,
                                    criterio_greedy="maximizar_volumen_tipo",
                                    titulo_solucion="Greedy maximizando volumen caja | Ordenamiento aleatorio")
soluciones_greedy.append(solucion_greedy12)
solucion_greedy12.resumen_general()

Situación original
--------------------------------------------------
Número de tipos de cajas distintos: 204
Costo packaging: 30166293.939999998
Costo flete: 179068800
Costo total: 209235093.94
Utilización de pallet promedio: 0.8320794116391749
Utilización de caja promedio: 1.0

Situación nueva
--------------------------------------------------
Grosor elegido: 4.5mm
Criterio elegido: Greedy maximizando volumen caja | Ordenamiento aleatorio
Número de tipos de cajas distintos: 52
Costo packaging: 29579858.359999973
Costo flete: 175576200
Costo total: 205156058.35999998
Utilización de pallet promedio: 0.8983362236911283
Utilización de caja promedio: 0.9557910211998384
Ahorro costo total: 1.94950%

#### **Comparación de criterios**

Finalmente, comparemos todos los criterios Greedy aplicados, y veamos cuál es el que obtuvo mejor ahorro con respecto a la situación base de AlixPartners.

In [ ]:
datos = []
    
datos.append({
    'solucion': 'Base',
    'grosor_mm': 5,
    'tipos_cajas': 204,
    'costo_packaging': 30166293.939999998,
    'costo_flete': 179068800,
    'costo_total': 209235093.94,
    'ahorro_%': 0.00000,
    'utilizacion_pallet_promedio': 0.8320794116391749,
    'utilizacion_caja_promedio': 1.0
})
    
for sol in soluciones_greedy:
    datos.append({
        'solucion': sol.titulo,
        'grosor_mm': sol.grosor_elegido,
        'tipos_cajas': sol.cantidad_tipos_cajas,
        'costo_packaging': sol.costo_packaging(),
        'costo_flete': sol.costo_flete(),
        'costo_total': sol.costo_total(),
        'ahorro_%': sol.ahorro_total_porcent() * 100,
        'utilizacion_pallet_promedio': sol.utilizacion_pallet_promedio(),
        'utilizacion_caja_promedio': sol.utilizacion_caja_promedio()
    })

df_comparacion = pd.DataFrame(datos)
df_comparacion

,solucion,grosor_mm,tipos_cajas,costo_packaging,costo_flete,costo_total,ahorro_%,utilizacion_pallet_promedio,utilizacion_caja_promedio
0,Base,4.5,204,3.016629e+07,179068800,2.092351e+08,0.000000,0.832079,1.000000
1,Greedy minimizando costo total | Ordenamiento ...,4.5,119,3.016946e+07,166868700,1.970382e+08,5.829296,0.913388,0.991290
2,Greedy minimizando costo flete | Ordenamiento ...,4.5,167,3.104671e+07,166867200,1.979139e+08,5.410748,0.907366,0.998045
3,Greedy maximizando utilizacion pallet | Ordena...,4.5,75,2.986172e+07,167446950,1.973087e+08,5.700011,0.962658,0.934797
4,Greedy maximizando volumen caja | Ordenamiento...,4.5,51,2.970901e+07,172219500,2.019285e+08,3.492044,0.905426,0.970166
5,Greedy minimizando costo total | Ordenamiento ...,4.5,103,3.003534e+07,166875150,1.969105e+08,5.890312,0.914020,0.990541
6,Greedy minimizando costo flete | Ordenamiento ...,4.5,167,3.104671e+07,166867200,1.979139e+08,5.410748,0.907366,0.998045
7,Greedy maximizando utilizacion pallet | Ordena...,4.5,75,2.986172e+07,167446950,1.973087e+08,5.700011,0.962658,0.934797
8,Greedy maximizando volumen caja | Ordenamiento...,4.5,57,2.948024e+07,172333050,2.018133e+08,3.547112,0.902818,0.971046
9,Greedy minimizando costo total | Ordenamiento ...,4.5,116,3.008719e+07,166872900,1.969601e+08,5.866611,0.916534,0.987860
10,Greedy minimizando costo flete | Ordenamiento ...,4.5,167,3.104671e+07,166867200,1.979139e+08,5.410748,0.907366,0.998045
11,Greedy maximizando utilizacion pallet | Ordena...,4.5,75,2.986172e+07,167446950,1.973087e+08,5.700011,0.962658,0.934797
12,Greedy maximizando volumen caja | Ordenamiento...,4.5,52,2.957986e+07,175576200,2.051561e+08,1.949499,0.898336,0.955791