#### **OPTIMALIDAD DE LA SOLUCION - ALGORITMOS GREEDY**

In [1]:
import pandas as pd 
from importlib import reload
import random

import Clases.asignacion as asignacion_module
reload(asignacion_module)
from Clases.asignacion import Asignacion

import Clases.caja as caja_module
reload(caja_module)
from Clases.caja import Caja

import Clases.producto as producto_module
reload(producto_module)
from Clases.producto import Producto

import Clases.solucion as solucion_module
reload(solucion_module)
from Clases.solucion import Solucion

catalogo_productos = pd.read_csv("Datos-finales/catalogo_productos.csv")
operaciones_planta = pd.read_csv("Datos-finales/operaciones_planta.csv")

cajas_nuevas = pd.read_csv("4r.cajas_nuevas.csv")
factibilidad = pd.read_csv("Factibilidad/factibilidad_5mm.csv")

Empecemos guardando los productos y tipos de cajas en listas en el estado actual, para cargarlos luego a las soluciones. Almacenamos también las cajas asignables a cada producto en un diccionario.

In [2]:
def guardar_cajas_y_productos(grosor=5):
    
    cajas = {
        row["caja_tipo_id"]: Caja(
            caja_id=row["caja_tipo_id"],
            dim_interior_ancho=row["caja_interior_ancho"],
            dim_interior_largo=row["caja_interior_largo"],
            dim_interior_alto=row["caja_interior_alto"]
        )
        for _, row in cajas_nuevas.iterrows()
    }

    prod_op_merge = catalogo_productos.merge(operaciones_planta, on="codigo_producto")
    productos = {
        row["codigo_producto"]: Producto(
            codigo_producto = row['codigo_producto'],
            cantidad_paquetes = row['cantidad_paquetes'],
            peso_paquete = row['peso_neto_paquete'],
            demanda_buenos_aires = row['volumen_producto_planta_buenos_aires'],
            demanda_curitiba = row['volumen_producto_planta_curitiba'],
            demanda_santiago = row['volumen_producto_planta_santiago'],
            demanda_monterrey = row['volumen_producto_planta_monterrey'],
            demanda_bakersfield = row['volumen_producto_planta_bakersfield'],
            dim_producto_ancho = row['dim_producto_ancho'], 
            dim_producto_largo = row['dim_producto_largo'],
            dim_producto_alto = row['dim_producto_alto']
        )
        for _, row in prod_op_merge.iterrows()
    }
    
    cajas_asignables_por_producto = {}

    for codigo, group in factibilidad.groupby('codigo_producto'):
        # Obtener IDs de los tipos de cajas
        cajas_ids_unicos = list(group['caja_tipo_id'].unique())
        
        cajas_producto = []
        for caja_id in cajas_ids_unicos:
            cajas_producto.append(caja_id)
            
        cajas_asignables_por_producto[codigo] = cajas_producto
                
    # Elegir grosor
    for caja_id, caja in cajas.items():
        caja.elegir_grosor(grosor_mm=grosor)
        
    return cajas, productos, cajas_asignables_por_producto

#### **Función Greedy**

Crearemos una función genérica para las soluciones Greedy, considerando los criterios que veamos útiles para el algoritmo.

In [3]:
def solucion_greedy(cajas, lista_productos_ordenados, cajas_asignables_por_producto, titulo_solucion, criterio_greedy, 
                    grosor=5):
    
    solucion = Solucion(grosor, titulo_solucion)

    for codigo_producto in lista_productos_ordenados:
        producto = productos[codigo_producto]
        metricas = {}  # caja_id -> (volumen_total, costo_packaging, costo_flete, costo_total, utilizacion_pallet)
        
        for caja_id in cajas_asignables_por_producto[codigo_producto]:
            caja = cajas[caja_id]
            
            # Volumen requerido actual (antes de asignar este producto)
            volumen_total = caja.unidades_total_requeridas()
            utilizacion_pallet = caja.utilizacion_pallet()
            
            # Costo simulado de asignar este producto a esta caja
            asignacion = Asignacion(producto, caja)
            caja.asignar_producto(producto)
            
            # Calculamos los costos del producto utilizando ese tipo de caja
            costo_packaging = asignacion.costo_packaging_producto_total()
            costo_flete = 150 * asignacion.cant_pallets_requeridas()
            costo_total = costo_packaging + costo_flete
            metricas[caja_id] = (volumen_total, costo_packaging, costo_flete, costo_total, utilizacion_pallet)
            
            # Revertimos la asignación para que no se aplique un descuento posterior
            caja.revocar_producto(producto)
        
        # Criterios a elegir
        if criterio_greedy == "minimizar_costo_total":
            caja_id_optima = min(metricas, key=lambda id: (metricas[id][3]))
        elif criterio_greedy == "maximizar_volumen_tipo":        
            caja_id_optima = max(metricas, key=lambda id: (metricas[id][0], -metricas[id][3])) # Desempate con costo minimo total
        elif criterio_greedy == "minimizar_costo_flete":
            caja_id_optima = min(metricas, key=lambda id: (metricas[id][2]))
        elif criterio_greedy == "maximizar_utilizacion_pallet":
            caja_id_optima = max(metricas, key=lambda id: (metricas[id][4]))
        
        caja_optima = cajas[caja_id_optima]
        asignacion = Asignacion(producto, caja_optima)
        solucion.agregar_asignacion(asignacion)    
    
    return solucion

#### **Greedy 1: Ordenamiento de productos según la cantidad de cajas asignables**

La idea ahora sería comparar las soluciones determinadas a partir de cada criterio Greedy, ordenando antes los productos según la cantidad de cajas asignables, de menor de mayor.

De esta manera, el algoritmo se ejecutaría gradualmente abriéndose en cada vez más posibilidades de cajas asignables.

In [4]:
def ordenar_por_cajas_asignables(asignaciones_por_producto):
    '''
    Ordenamos los productos según la cantidad de cajas asignables de menor a mayor
    '''
    productos_conteo = []

    for codigo_producto, cajas_asignables in asignaciones_por_producto.items():
        cantidad_cajas = len(cajas_asignables)  # Número de cajas asignables para este producto    
        productos_conteo.append({
            'codigo_producto': codigo_producto,
            'cantidad_cajas_asignables': cantidad_cajas
        })

    # Ordenar de menor a mayor cantidad de cajas
    productos_ordenados = sorted(
        productos_conteo,
        key=lambda x: x['cantidad_cajas_asignables'],
        reverse=False
    )

    lista_productos_ordenados = [item['codigo_producto'] for item in productos_ordenados]
    return lista_productos_ordenados

Guardaremos todas las soluciones greedy en una lista, para facilitar la comparación posterior.

In [5]:
soluciones_greedy = []

In [6]:
cajas, productos, asignaciones_por_producto = guardar_cajas_y_productos()
lista_productos_ordenados = ordenar_por_cajas_asignables(asignaciones_por_producto)

solucion_greedy1 = solucion_greedy(cajas, lista_productos_ordenados, asignaciones_por_producto, 
                                   criterio_greedy="minimizar_costo_total",
                                   titulo_solucion="Greedy minimizando costo total | Ordenamiento según #cajas asignables")
soluciones_greedy.append(solucion_greedy1)
solucion_greedy1.resumen_general()

Situación original
--------------------------------------------------
Número de tipos de cajas distintos: 204
Costo packaging: 30166293.939999998
Costo flete: 179068800
Costo total: 209235093.94
Utilización de pallet promedio: 0.8320794116391749
Utilización de caja promedio: 1.0

Situación nueva
--------------------------------------------------
Grosor elegido: 5mm
Criterio elegido: Greedy minimizando costo total | Ordenamiento según #cajas asignables
Número de tipos de cajas distintos: 118
Costo packaging: 32514589.16999998
Costo flete: 167188950
Costo total: 199703539.17
Utilización de pallet promedio: 0.9208028157553615
Utilización de caja promedio: 0.9905456400669789
Ahorro costo total: 4.55543%

In [7]:
solucion_greedy1.resumen_por_asignacion()

,codigo_producto,volumen_producto_total,demanda_total,caja_id,utilizacion_pallet,utilizacion_caja,descuento_buenos_aires,descuento_curitiba,descuento_santiago,descuento_monterrey,descuento_bakersfield,costo_packaging,cant_pallets,costo_flete,costo_total
0,BR0001,1546613,1546613,CAJ0358186,0.866667,0.979324,0.1,-0.3,-0.2,-0.1,-0.2,772060.94,38667,5800050,6572110.94
1,BR0002,139211,139211,CAJ0291786,0.933333,0.995487,-0.3,-0.2,-0.3,0.1,-0.2,77958.16,2901,435150,513108.16
2,BR0003,172506,172506,CAJ0072296,0.955421,1.000000,0.1,0.1,0.1,0.1,-0.2,96603.36,2157,323550,420153.36
3,BR0004,271715,271715,CAJ0212936,0.941111,0.998128,0.1,-0.3,0.1,-0.1,-0.3,133140.35,4853,727950,861090.35
4,BR0005,7586,7586,CAJ0258586,0.880000,0.972249,-0.1,-0.2,-0.3,0.0,-0.1,4248.16,159,23850,28098.16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
422,BR0417,2761,2761,CAJ0175036,0.922548,0.993695,-0.2,-0.2,-0.2,-0.3,0.1,1546.16,44,6600,8146.16
423,BR0418,3942,3942,CAJ0175036,0.922548,0.993695,-0.2,-0.2,-0.2,-0.3,0.1,2207.52,62,9300,11507.52
424,BR0419,43300,43300,CAJ0105050,0.945250,0.998695,0.1,0.1,0.1,0.0,0.1,30310.00,602,90300,120610.00
425,BR0420,205852,205852,CAJ0121386,0.957000,0.995824,-0.3,-0.2,0.1,-0.3,0.1,102563.37,2860,429000,531563.37
426,BR0421,145803,145803,CAJ0158736,0.928000,0.997909,0.1,-0.3,-0.3,-0.3,-0.3,71443.47,2279,341850,413293.47

In [8]:
cajas, productos, asignaciones_por_producto = guardar_cajas_y_productos()
lista_productos_ordenados = ordenar_por_cajas_asignables(asignaciones_por_producto)

solucion_greedy2 = solucion_greedy(cajas, lista_productos_ordenados, asignaciones_por_producto, 
                                   criterio_greedy="minimizar_costo_flete",
                                   titulo_solucion="Greedy minimizando costo flete | Ordenamiento según #cajas asignables")
soluciones_greedy.append(solucion_greedy2)
solucion_greedy2.resumen_general()

Situación original
--------------------------------------------------
Número de tipos de cajas distintos: 204
Costo packaging: 30166293.939999998
Costo flete: 179068800
Costo total: 209235093.94
Utilización de pallet promedio: 0.8320794116391749
Utilización de caja promedio: 1.0

Situación nueva
--------------------------------------------------
Grosor elegido: 5mm
Criterio elegido: Greedy minimizando costo flete | Ordenamiento según #cajas asignables
Número de tipos de cajas distintos: 166
Costo packaging: 33434918.36999999
Costo flete: 167175300
Costo total: 200610218.37
Utilización de pallet promedio: 0.9144684694896712
Utilización de caja promedio: 0.9978765040183482
Ahorro costo total: 4.12210%

In [9]:
cajas, productos, asignaciones_por_producto = guardar_cajas_y_productos()
lista_productos_ordenados = ordenar_por_cajas_asignables(asignaciones_por_producto)

solucion_greedy3 = solucion_greedy(cajas, lista_productos_ordenados, asignaciones_por_producto,
                                   criterio_greedy="maximizar_utilizacion_pallet",
                                   titulo_solucion="Greedy maximizando utilizacion pallet | Ordenamiento según #cajas asignables")
soluciones_greedy.append(solucion_greedy3)
solucion_greedy3.resumen_general()

Situación original
--------------------------------------------------
Número de tipos de cajas distintos: 204
Costo packaging: 30166293.939999998
Costo flete: 179068800
Costo total: 209235093.94
Utilización de pallet promedio: 0.8320794116391749
Utilización de caja promedio: 1.0

Situación nueva
--------------------------------------------------
Grosor elegido: 5mm
Criterio elegido: Greedy maximizando utilizacion pallet | Ordenamiento según #cajas asignables
Número de tipos de cajas distintos: 67
Costo packaging: 32074164.21999996
Costo flete: 167331450
Costo total: 199405614.21999997
Utilización de pallet promedio: 0.9755084012908097
Utilización de caja promedio: 0.9321327952418127
Ahorro costo total: 4.69782%

In [10]:
cajas, productos, asignaciones_por_producto = guardar_cajas_y_productos()
lista_productos_ordenados = ordenar_por_cajas_asignables(asignaciones_por_producto)

solucion_greedy4 = solucion_greedy(cajas, lista_productos_ordenados, asignaciones_por_producto, 
                                   criterio_greedy="maximizar_volumen_tipo",
                                   titulo_solucion="Greedy maximizando volumen caja | Ordenamiento según #cajas asignables")
soluciones_greedy.append(solucion_greedy4)
solucion_greedy4.resumen_general()

Situación original
--------------------------------------------------
Número de tipos de cajas distintos: 204
Costo packaging: 30166293.939999998
Costo flete: 179068800
Costo total: 209235093.94
Utilización de pallet promedio: 0.8320794116391749
Utilización de caja promedio: 1.0

Situación nueva
--------------------------------------------------
Grosor elegido: 5mm
Criterio elegido: Greedy maximizando volumen caja | Ordenamiento según #cajas asignables
Número de tipos de cajas distintos: 46
Costo packaging: 31800668.54999997
Costo flete: 172229250
Costo total: 204029918.54999998
Utilización de pallet promedio: 0.9209225460984984
Utilización de caja promedio: 0.9614337358705111
Ahorro costo total: 2.48772%

#### **Greedy 2: Ordenamiento de productos según su demanda total**

Repetiremos todos los criterios Greedy ordenando ahora los productos según su demanda total, de mayor a menor, para luego comparar con los resultados obtenidos anteriormente.

De esta manera, aceleraríamos la aplicación de descuentos para reducir el costo packaging lo antes posible.

In [11]:
def ordenar_por_demanda_total(productos):
    '''
    Ordenamos los productos según la demanda total de mayor a menor
    '''
    productos_ordenados = sorted(
        productos.values(),
        key=lambda p: p.demanda_total(),
        reverse=True
    )
    return [p.codigo_producto for p in productos_ordenados]

In [12]:
cajas, productos, asignaciones_por_producto = guardar_cajas_y_productos()
lista_productos_ordenados = ordenar_por_demanda_total(productos)

solucion_greedy5 = solucion_greedy(cajas, lista_productos_ordenados, asignaciones_por_producto, 
                                   criterio_greedy="minimizar_costo_total",
                                   titulo_solucion="Greedy minimizando costo total | Ordenamiento según demanda total")
soluciones_greedy.append(solucion_greedy5)
solucion_greedy5.resumen_general()

Situación original
--------------------------------------------------
Número de tipos de cajas distintos: 204
Costo packaging: 30166293.939999998
Costo flete: 179068800
Costo total: 209235093.94
Utilización de pallet promedio: 0.8320794116391749
Utilización de caja promedio: 1.0

Situación nueva
--------------------------------------------------
Grosor elegido: 5mm
Criterio elegido: Greedy minimizando costo total | Ordenamiento según demanda total
Número de tipos de cajas distintos: 98
Costo packaging: 32252558.729999986
Costo flete: 167200350
Costo total: 199452908.73
Utilización de pallet promedio: 0.9203794575944257
Utilización de caja promedio: 0.9910507134133376
Ahorro costo total: 4.67521%

In [13]:
cajas, productos, asignaciones_por_producto = guardar_cajas_y_productos()
lista_productos_ordenados = ordenar_por_demanda_total(productos)

solucion_greedy6 = solucion_greedy(cajas, lista_productos_ordenados, asignaciones_por_producto, 
                                   criterio_greedy="minimizar_costo_flete",
                                   titulo_solucion="Greedy minimizando costo flete | Ordenamiento según demanda total")
soluciones_greedy.append(solucion_greedy6)
solucion_greedy6.resumen_general()

Situación original
--------------------------------------------------
Número de tipos de cajas distintos: 204
Costo packaging: 30166293.939999998
Costo flete: 179068800
Costo total: 209235093.94
Utilización de pallet promedio: 0.8320794116391749
Utilización de caja promedio: 1.0

Situación nueva
--------------------------------------------------
Grosor elegido: 5mm
Criterio elegido: Greedy minimizando costo flete | Ordenamiento según demanda total
Número de tipos de cajas distintos: 166
Costo packaging: 33434918.369999968
Costo flete: 167175300
Costo total: 200610218.36999997
Utilización de pallet promedio: 0.9144684694896711
Utilización de caja promedio: 0.9978765040183474
Ahorro costo total: 4.12210%

In [14]:
cajas, productos, asignaciones_por_producto = guardar_cajas_y_productos()
lista_productos_ordenados = ordenar_por_demanda_total(productos)

solucion_greedy7 = solucion_greedy(cajas, lista_productos_ordenados, asignaciones_por_producto, 
                                   criterio_greedy="maximizar_utilizacion_pallet",
                                   titulo_solucion="Greedy maximizando utilizacion pallet | Ordenamiento según demanda total")
soluciones_greedy.append(solucion_greedy7)
solucion_greedy7.resumen_general()

Situación original
--------------------------------------------------
Número de tipos de cajas distintos: 204
Costo packaging: 30166293.939999998
Costo flete: 179068800
Costo total: 209235093.94
Utilización de pallet promedio: 0.8320794116391749
Utilización de caja promedio: 1.0

Situación nueva
--------------------------------------------------
Grosor elegido: 5mm
Criterio elegido: Greedy maximizando utilizacion pallet | Ordenamiento según demanda total
Número de tipos de cajas distintos: 67
Costo packaging: 32074164.219999947
Costo flete: 167331450
Costo total: 199405614.21999994
Utilización de pallet promedio: 0.9755084012908096
Utilización de caja promedio: 0.9321327952418134
Ahorro costo total: 4.69782%

In [15]:
cajas, productos, asignaciones_por_producto = guardar_cajas_y_productos()
lista_productos_ordenados = ordenar_por_demanda_total(productos)

solucion_greedy8 = solucion_greedy(cajas, lista_productos_ordenados, asignaciones_por_producto, 
                                   criterio_greedy="maximizar_volumen_tipo",
                                   titulo_solucion="Greedy maximizando volumen caja | Ordenamiento según demanda total")
soluciones_greedy.append(solucion_greedy8)
solucion_greedy8.resumen_general()

Situación original
--------------------------------------------------
Número de tipos de cajas distintos: 204
Costo packaging: 30166293.939999998
Costo flete: 179068800
Costo total: 209235093.94
Utilización de pallet promedio: 0.8320794116391749
Utilización de caja promedio: 1.0

Situación nueva
--------------------------------------------------
Grosor elegido: 5mm
Criterio elegido: Greedy maximizando volumen caja | Ordenamiento según demanda total
Número de tipos de cajas distintos: 39
Costo packaging: 31486815.14999998
Costo flete: 173489850
Costo total: 204976665.14999998
Utilización de pallet promedio: 0.9071370161831029
Utilización de caja promedio: 0.9673919041175184
Ahorro costo total: 2.03524%

#### **Greedy 3: Ordenamiento de productos de forma aleatoria**

Ordenemos los productos de forma aleatoria, fijando una semilla para la reproducibilidad, y comparemos los resultados con los anteriores casos.

In [16]:
def ordenar_aleatorio(productos, seed):
    random.seed(seed)
    lista_productos = list(productos.values())
    random.shuffle(lista_productos)
    return [p.codigo_producto for p in lista_productos]

In [17]:
cajas, productos, asignaciones_por_producto = guardar_cajas_y_productos()
lista_productos_ordenados = ordenar_aleatorio(productos, seed=2708)

solucion_greedy9 = solucion_greedy(cajas, lista_productos_ordenados, asignaciones_por_producto, 
                                   criterio_greedy="minimizar_costo_total",
                                   titulo_solucion="Greedy minimizando costo total | Ordenamiento aleatorio")
soluciones_greedy.append(solucion_greedy9)
solucion_greedy9.resumen_general()

Situación original
--------------------------------------------------
Número de tipos de cajas distintos: 204
Costo packaging: 30166293.939999998
Costo flete: 179068800
Costo total: 209235093.94
Utilización de pallet promedio: 0.8320794116391749
Utilización de caja promedio: 1.0

Situación nueva
--------------------------------------------------
Grosor elegido: 5mm
Criterio elegido: Greedy minimizando costo total | Ordenamiento aleatorio
Número de tipos de cajas distintos: 112
Costo packaging: 32368081.269999992
Costo flete: 167190600
Costo total: 199558681.26999998
Utilización de pallet promedio: 0.9212546375775664
Utilización de caja promedio: 0.9901819592746428
Ahorro costo total: 4.62466%

In [18]:
cajas, productos, asignaciones_por_producto = guardar_cajas_y_productos()
lista_productos_ordenados = ordenar_aleatorio(productos, seed=2708)

solucion_greedy10 = solucion_greedy(cajas, lista_productos_ordenados, asignaciones_por_producto, 
                                   criterio_greedy="minimizar_costo_flete",
                                   titulo_solucion="Greedy minimizando costo flete | Ordenamiento aleatorio")
soluciones_greedy.append(solucion_greedy10)
solucion_greedy10.resumen_general()

Situación original
--------------------------------------------------
Número de tipos de cajas distintos: 204
Costo packaging: 30166293.939999998
Costo flete: 179068800
Costo total: 209235093.94
Utilización de pallet promedio: 0.8320794116391749
Utilización de caja promedio: 1.0

Situación nueva
--------------------------------------------------
Grosor elegido: 5mm
Criterio elegido: Greedy minimizando costo flete | Ordenamiento aleatorio
Número de tipos de cajas distintos: 166
Costo packaging: 33434918.36999999
Costo flete: 167175300
Costo total: 200610218.37
Utilización de pallet promedio: 0.9144684694896706
Utilización de caja promedio: 0.9978765040183478
Ahorro costo total: 4.12210%

In [19]:
cajas, productos, asignaciones_por_producto = guardar_cajas_y_productos()
lista_productos_ordenados = ordenar_aleatorio(productos, seed=2708)

solucion_greedy11 = solucion_greedy(cajas, lista_productos_ordenados, asignaciones_por_producto, 
                                   criterio_greedy="maximizar_utilizacion_pallet",
                                   titulo_solucion="Greedy maximizando utilizacion pallet | Ordenamiento aleatorio")
soluciones_greedy.append(solucion_greedy11)
solucion_greedy11.resumen_general()

Situación original
--------------------------------------------------
Número de tipos de cajas distintos: 204
Costo packaging: 30166293.939999998
Costo flete: 179068800
Costo total: 209235093.94
Utilización de pallet promedio: 0.8320794116391749
Utilización de caja promedio: 1.0

Situación nueva
--------------------------------------------------
Grosor elegido: 5mm
Criterio elegido: Greedy maximizando utilizacion pallet | Ordenamiento aleatorio
Número de tipos de cajas distintos: 67
Costo packaging: 32074164.219999973
Costo flete: 167331450
Costo total: 199405614.21999997
Utilización de pallet promedio: 0.9755084012908096
Utilización de caja promedio: 0.9321327952418136
Ahorro costo total: 4.69782%

In [20]:
cajas, productos, asignaciones_por_producto = guardar_cajas_y_productos()
lista_productos_ordenados = ordenar_aleatorio(productos, seed=2708)

solucion_greedy12 = solucion_greedy(cajas, lista_productos_ordenados, asignaciones_por_producto, 
                                   criterio_greedy="maximizar_volumen_tipo",
                                   titulo_solucion="Greedy maximizando volumen caja | Ordenamiento aleatorio")
soluciones_greedy.append(solucion_greedy12)
solucion_greedy12.resumen_general()

Situación original
--------------------------------------------------
Número de tipos de cajas distintos: 204
Costo packaging: 30166293.939999998
Costo flete: 179068800
Costo total: 209235093.94
Utilización de pallet promedio: 0.8320794116391749
Utilización de caja promedio: 1.0

Situación nueva
--------------------------------------------------
Grosor elegido: 5mm
Criterio elegido: Greedy maximizando volumen caja | Ordenamiento aleatorio
Número de tipos de cajas distintos: 43
Costo packaging: 31671182.339999992
Costo flete: 177710100
Costo total: 209381282.34
Utilización de pallet promedio: 0.9008067284334074
Utilización de caja promedio: 0.9511532369390443
Ahorro costo total: -0.06987%

#### **Comparación de criterios**

Finalmente, comparemos todos los criterios Greedy aplicados, y veamos cuál es el que obtuvo mejor ahorro con respecto a la situación base de AlixPartners.

In [21]:
datos = []
    
datos.append({
    'solucion': 'Base',
    'grosor_mm': 5,
    'tipos_cajas': 204,
    'costo_packaging': 30166293.939999998,
    'costo_flete': 179068800,
    'costo_total': 209235093.94,
    'ahorro_%': 0.00000,
    'utilizacion_pallet_promedio': 0.8320794116391749,
    'utilizacion_caja_promedio': 1.0
})
    
for sol in soluciones_greedy:
    datos.append({
        'solucion': sol.titulo,
        'grosor_mm': sol.grosor_elegido,
        'tipos_cajas': sol.cantidad_tipos_cajas,
        'costo_packaging': sol.costo_packaging(),
        'costo_flete': sol.costo_flete(),
        'costo_total': sol.costo_total(),
        'ahorro_%': sol.ahorro_total_porcent() * 100,
        'utilizacion_pallet_promedio': sol.utilizacion_pallet_promedio(),
        'utilizacion_caja_promedio': sol.utilizacion_caja_promedio()
    })

df_comparacion = pd.DataFrame(datos)
df_comparacion

,solucion,grosor_mm,tipos_cajas,costo_packaging,costo_flete,costo_total,ahorro_%,utilizacion_pallet_promedio,utilizacion_caja_promedio
0,Base,5,204,30166293.94,179068800,2.092351e+08,0.000000,0.832079,1.000000
1,Greedy minimizando costo total | Ordenamiento ...,5,118,32514589.17,167188950,1.997035e+08,4.555428,0.920803,0.990546
2,Greedy minimizando costo flete | Ordenamiento ...,5,166,33434918.37,167175300,2.006102e+08,4.122098,0.914468,0.997877
3,Greedy maximizando utilizacion pallet | Ordena...,5,67,32074164.22,167331450,1.994056e+08,4.697816,0.975508,0.932133
4,Greedy maximizando volumen caja | Ordenamiento...,5,46,31800668.55,172229250,2.040299e+08,2.487716,0.920923,0.961434
5,Greedy minimizando costo total | Ordenamiento ...,5,98,32252558.73,167200350,1.994529e+08,4.675212,0.920379,0.991051
6,Greedy minimizando costo flete | Ordenamiento ...,5,166,33434918.37,167175300,2.006102e+08,4.122098,0.914468,0.997877
7,Greedy maximizando utilizacion pallet | Ordena...,5,67,32074164.22,167331450,1.994056e+08,4.697816,0.975508,0.932133
8,Greedy maximizando volumen caja | Ordenamiento...,5,39,31486815.15,173489850,2.049767e+08,2.035236,0.907137,0.967392
9,Greedy minimizando costo total | Ordenamiento ...,5,112,32368081.27,167190600,1.995587e+08,4.624660,0.921255,0.990182
10,Greedy minimizando costo flete | Ordenamiento ...,5,166,33434918.37,167175300,2.006102e+08,4.122098,0.914468,0.997877
11,Greedy maximizando utilizacion pallet | Ordena...,5,67,32074164.22,167331450,1.994056e+08,4.697816,0.975508,0.932133
12,Greedy maximizando volumen caja | Ordenamiento...,5,43,31671182.34,177710100,2.093813e+08,-0.069868,0.900807,0.951153