#### **OPTIMALIDAD DE LA SOLUCION - ALGORITMOS GREEDY**

In [13]:
import pandas as pd 
from importlib import reload

import Clases.asignacion as asignacion_module
reload(asignacion_module)
from Clases.asignacion import Asignacion

import Clases.caja as caja_module
reload(caja_module)
from Clases.caja import Caja

import Clases.producto as producto_module
reload(producto_module)
from Clases.producto import Producto

import Clases.solucion as solucion_module
reload(solucion_module)
from Clases.solucion import Solucion

catalogo_productos = pd.read_csv("Datos-finales/catalogo_productos.csv")
operaciones_planta = pd.read_csv("Datos-finales/operaciones_planta.csv")

cajas_nuevas = pd.read_csv("4r.cajas_nuevas.csv")
factibilidad = pd.read_csv("Factibilidad/factibilidad_3mm.csv")

Empecemos guardando los productos y tipos de cajas en listas en el estado actual, para cargarlos luego a las soluciones. Almacenamos también las cajas asignables a cada producto en un diccionario.

In [14]:
def guardar_cajas_y_productos(grosor=3):
    
    cajas = {
        row["caja_tipo_id"]: Caja(
            caja_id=row["caja_tipo_id"],
            dim_interior_ancho=row["caja_interior_ancho"],
            dim_interior_largo=row["caja_interior_largo"],
            dim_interior_alto=row["caja_interior_alto"]
        )
        for _, row in cajas_nuevas.iterrows()
    }

    prod_op_merge = catalogo_productos.merge(operaciones_planta, on="codigo_producto")
    productos = {
        row["codigo_producto"]: Producto(
            codigo_producto = row['codigo_producto'],
            cantidad_paquetes = row['cantidad_paquetes'],
            peso_paquete = row['peso_neto_paquete'],
            demanda_buenos_aires = row['volumen_producto_planta_buenos_aires'],
            demanda_curitiba = row['volumen_producto_planta_curitiba'],
            demanda_santiago = row['volumen_producto_planta_santiago'],
            demanda_monterrey = row['volumen_producto_planta_monterrey'],
            demanda_bakersfield = row['volumen_producto_planta_bakersfield'],
            dim_producto_ancho = row['dim_producto_ancho'], 
            dim_producto_largo = row['dim_producto_largo'],
            dim_producto_alto = row['dim_producto_alto']
        )
        for _, row in prod_op_merge.iterrows()
    }
    
    cajas_asignables_por_producto = {}

    for codigo, group in factibilidad.groupby('codigo_producto'):
        # Obtener IDs de los tipos de cajas
        cajas_ids_unicos = list(group['caja_tipo_id'].unique())
        
        cajas_producto = []
        for caja_id in cajas_ids_unicos:
            cajas_producto.append(caja_id)
            
        cajas_asignables_por_producto[codigo] = cajas_producto
                
    # Elegir grosor
    for caja_id, caja in cajas.items():
        caja.elegir_grosor(grosor_mm=grosor)
        
    return cajas, productos, cajas_asignables_por_producto

#### **Función Greedy**

Crearemos una función genérica para las soluciones Greedy, considerando los criterios que veamos útiles para el algoritmo.

In [15]:
def solucion_greedy(cajas, lista_productos_ordenados, cajas_asignables_por_producto, titulo_solucion, criterio_greedy, 
                    grosor=3):
    
    solucion = Solucion(grosor, titulo_solucion)

    for codigo_producto in lista_productos_ordenados:
        producto = productos[codigo_producto]
        metricas = {}  # caja_id -> (volumen_total, costo_packaging, costo_flete, costo_total, utilizacion_pallet)
        
        for caja_id in cajas_asignables_por_producto[codigo_producto]:
            caja = cajas[caja_id]
            
            # Volumen requerido actual (antes de asignar este producto)
            volumen_total = caja.unidades_total_requeridas()
            utilizacion_pallet = caja.utilizacion_pallet()
            
            # Costo simulado de asignar este producto a esta caja
            asignacion = Asignacion(producto, caja)
            caja.asignar_producto(producto)
            
            # Calculamos los costos del producto utilizando ese tipo de caja
            costo_packaging = asignacion.costo_packaging_producto_total()
            costo_flete = 150 * asignacion.cant_pallets_requeridas()
            costo_total = costo_packaging + costo_flete
            metricas[caja_id] = (volumen_total, costo_packaging, costo_flete, costo_total, utilizacion_pallet)
            
            # Revertimos la asignación para que no se aplique un descuento posterior
            caja.revocar_producto(producto)
        
        # Criterios a elegir
        if criterio_greedy == "minimizar_costo_total":
            caja_id_optima = min(metricas, key=lambda id: (metricas[id][3]))
        elif criterio_greedy == "maximizar_volumen_tipo":        
            caja_id_optima = max(metricas, key=lambda id: (metricas[id][0], -metricas[id][3])) # Desempate con costo minimo total
        elif criterio_greedy == "minimizar_costo_flete":
            caja_id_optima = min(metricas, key=lambda id: (metricas[id][2]))
        elif criterio_greedy == "maximizar_utilizacion_pallet":
            caja_id_optima = max(metricas, key=lambda id: (metricas[id][4]))
        
        caja_optima = cajas[caja_id_optima]
        asignacion = Asignacion(producto, caja_optima)
        solucion.agregar_asignacion(asignacion)    
    
    return solucion

#### **Greedy 1: Ordenamiento de productos según la cantidad de cajas asignables**

La idea ahora sería comparar las soluciones determinadas a partir de cada criterio Greedy, ordenando antes los productos según la cantidad de cajas asignables, de menor de mayor.

De esta manera, el algoritmo se ejecutaría gradualmente abriéndose en cada vez más posibilidades de cajas asignables.

In [16]:
def ordenar_por_cajas_asignables(asignaciones_por_producto):
    '''
    Ordenamos los productos según la cantidad de cajas asignables de menor a mayor
    '''
    productos_conteo = []

    for codigo_producto, cajas_asignables in asignaciones_por_producto.items():
        cantidad_cajas = len(cajas_asignables)  # Número de cajas asignables para este producto    
        productos_conteo.append({
            'codigo_producto': codigo_producto,
            'cantidad_cajas_asignables': cantidad_cajas
        })

    # Ordenar de menor a mayor cantidad de cajas
    productos_ordenados = sorted(
        productos_conteo,
        key=lambda x: x['cantidad_cajas_asignables'],
        reverse=False
    )

    lista_productos_ordenados = [item['codigo_producto'] for item in productos_ordenados]
    return lista_productos_ordenados

Guardaremos todas las soluciones greedy en una lista, para facilitar la comparación posterior.

In [17]:
soluciones_greedy = []

In [18]:
cajas, productos, asignaciones_por_producto = guardar_cajas_y_productos()
lista_productos_ordenados = ordenar_por_cajas_asignables(asignaciones_por_producto)

solucion_greedy1 = solucion_greedy(cajas, lista_productos_ordenados, asignaciones_por_producto, 
                                   criterio_greedy="minimizar_costo_total",
                                   titulo_solucion="Greedy minimizando costo total | Ordenamiento según #cajas asignables")
soluciones_greedy.append(solucion_greedy1)
solucion_greedy1.resumen_general()

Situación original
--------------------------------------------------
Número de tipos de cajas distintos: 204
Costo packaging: 30166293.939999998
Costo flete: 179068800
Costo total: 209235093.94
Utilización de pallet promedio: 0.8320794116391749
Utilización de caja promedio: 1.0

Situación nueva
--------------------------------------------------
Grosor elegido: 3mm
Criterio elegido: Greedy minimizando costo total | Ordenamiento según #cajas asignables
Número de tipos de cajas distintos: 119
Costo packaging: 27791103.59999999
Costo flete: 161188350
Costo total: 188979453.6
Utilización de pallet promedio: 0.9177550344646637
Utilización de caja promedio: 0.990524395427613
Ahorro costo total: 9.68080%

In [19]:
solucion_greedy1.resumen_por_asignacion()

,codigo_producto,volumen_producto_total,demanda_total,caja_id,utilizacion_pallet,utilizacion_caja,descuento_buenos_aires,descuento_curitiba,descuento_santiago,descuento_monterrey,descuento_bakersfield,costo_packaging,cant_pallets,costo_flete,costo_total
0,BR0001,1546613,1546613,CAJ2636692,1.000000,0.982212,0.1,-0.3,-0.3,-0.1,-0.3,660171.54,32223,4833450,5493621.54
1,BR0002,139211,139211,CAJ2138460,0.896667,0.997844,-0.3,-0.2,-0.3,0.1,-0.2,66821.28,2901,435150,501971.28
2,BR0003,172506,172506,CAJ0474235,0.913611,0.998406,0.1,0.1,0.1,0.1,-0.2,82802.88,2157,323550,406352.88
3,BR0004,271715,271715,CAJ1559770,0.903091,0.999418,0.1,-0.3,0.1,-0.1,-0.3,114120.30,4853,727950,842070.30
4,BR0005,7586,7586,CAJ1945596,0.999444,0.960631,-0.1,-0.2,-0.2,0.0,-0.2,3641.28,136,20400,24041.28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
422,BR0417,2761,2761,CAJ1795067,0.962033,0.998717,0.1,0.1,0.1,0.1,0.1,1822.26,40,6000,7822.26
423,BR0418,3942,3942,CAJ1795067,0.962033,0.998717,0.1,0.1,0.1,0.1,0.1,2601.72,57,8550,11151.72
424,BR0419,43300,43300,CAJ0724674,0.905000,0.997823,-0.2,0.1,0.1,0.0,0.1,25980.00,602,90300,116280.00
425,BR0420,205852,205852,CAJ0995093,0.911815,0.999769,-0.2,-0.2,0.1,-0.3,0.1,87911.46,2860,429000,516911.46
426,BR0421,145803,145803,CAJ1300461,0.888277,0.998933,0.1,-0.3,-0.2,-0.3,-0.3,61237.26,2279,341850,403087.26

In [20]:
cajas, productos, asignaciones_por_producto = guardar_cajas_y_productos()
lista_productos_ordenados = ordenar_por_cajas_asignables(asignaciones_por_producto)

solucion_greedy2 = solucion_greedy(cajas, lista_productos_ordenados, asignaciones_por_producto, 
                                   criterio_greedy="minimizar_costo_flete",
                                   titulo_solucion="Greedy minimizando costo flete | Ordenamiento según #cajas asignables")
soluciones_greedy.append(solucion_greedy2)
solucion_greedy2.resumen_general()

Situación original
--------------------------------------------------
Número de tipos de cajas distintos: 204
Costo packaging: 30166293.939999998
Costo flete: 179068800
Costo total: 209235093.94
Utilización de pallet promedio: 0.8320794116391749
Utilización de caja promedio: 1.0

Situación nueva
--------------------------------------------------
Grosor elegido: 3mm
Criterio elegido: Greedy minimizando costo flete | Ordenamiento según #cajas asignables
Número de tipos de cajas distintos: 182
Costo packaging: 28691260.799999986
Costo flete: 161171250
Costo total: 189862510.79999998
Utilización de pallet promedio: 0.9102406754058984
Utilización de caja promedio: 0.9989024157619177
Ahorro costo total: 9.25876%

In [21]:
cajas, productos, asignaciones_por_producto = guardar_cajas_y_productos()
lista_productos_ordenados = ordenar_por_cajas_asignables(asignaciones_por_producto)

solucion_greedy3 = solucion_greedy(cajas, lista_productos_ordenados, asignaciones_por_producto,
                                   criterio_greedy="maximizar_utilizacion_pallet",
                                   titulo_solucion="Greedy maximizando utilizacion pallet | Ordenamiento según #cajas asignables")
soluciones_greedy.append(solucion_greedy3)
solucion_greedy3.resumen_general()

Situación original
--------------------------------------------------
Número de tipos de cajas distintos: 204
Costo packaging: 30166293.939999998
Costo flete: 179068800
Costo total: 209235093.94
Utilización de pallet promedio: 0.8320794116391749
Utilización de caja promedio: 1.0

Situación nueva
--------------------------------------------------
Grosor elegido: 3mm
Criterio elegido: Greedy maximizando utilizacion pallet | Ordenamiento según #cajas asignables
Número de tipos de cajas distintos: 76
Costo packaging: 27406334.33999999
Costo flete: 161380650
Costo total: 188786984.33999997
Utilización de pallet promedio: 0.9593515126880586
Utilización de caja promedio: 0.9445527162171277
Ahorro costo total: 9.77279%

In [22]:
cajas, productos, asignaciones_por_producto = guardar_cajas_y_productos()
lista_productos_ordenados = ordenar_por_cajas_asignables(asignaciones_por_producto)

solucion_greedy4 = solucion_greedy(cajas, lista_productos_ordenados, asignaciones_por_producto, 
                                   criterio_greedy="maximizar_volumen_tipo",
                                   titulo_solucion="Greedy maximizando volumen caja | Ordenamiento según #cajas asignables")
soluciones_greedy.append(solucion_greedy4)
solucion_greedy4.resumen_general()

Situación original
--------------------------------------------------
Número de tipos de cajas distintos: 204
Costo packaging: 30166293.939999998
Costo flete: 179068800
Costo total: 209235093.94
Utilización de pallet promedio: 0.8320794116391749
Utilización de caja promedio: 1.0

Situación nueva
--------------------------------------------------
Grosor elegido: 3mm
Criterio elegido: Greedy maximizando volumen caja | Ordenamiento según #cajas asignables
Número de tipos de cajas distintos: 50
Costo packaging: 27329547.17999998
Costo flete: 167754600
Costo total: 195084147.17999998
Utilización de pallet promedio: 0.896105895350228
Utilización de caja promedio: 0.9722437038546999
Ahorro costo total: 6.76318%

#### **Greedy 2: Ordenamiento de productos según su demanda total**

Repetiremos todos los criterios Greedy ordenando ahora los productos según su demanda total, de mayor a menor, para luego comparar con los resultados obtenidos anteriormente.

De esta manera, aceleraríamos la aplicación de descuentos para reducir el costo packaging lo antes posible.

In [23]:
def ordenar_por_demanda_total(productos):
    '''
    Ordenamos los productos según la demanda total de mayor a menor
    '''
    productos_ordenados = sorted(
        productos.values(),
        key=lambda p: p.demanda_total(),
        reverse=True
    )
    return [p.codigo_producto for p in productos_ordenados]

In [24]:
cajas, productos, asignaciones_por_producto = guardar_cajas_y_productos()
lista_productos_ordenados = ordenar_por_demanda_total(productos)

solucion_greedy5 = solucion_greedy(cajas, lista_productos_ordenados, asignaciones_por_producto, 
                                   criterio_greedy="minimizar_costo_total",
                                   titulo_solucion="Greedy minimizando costo total | Ordenamiento según demanda total")
soluciones_greedy.append(solucion_greedy5)
solucion_greedy5.resumen_general()

Situación original
--------------------------------------------------
Número de tipos de cajas distintos: 204
Costo packaging: 30166293.939999998
Costo flete: 179068800
Costo total: 209235093.94
Utilización de pallet promedio: 0.8320794116391749
Utilización de caja promedio: 1.0

Situación nueva
--------------------------------------------------
Grosor elegido: 3mm
Criterio elegido: Greedy minimizando costo total | Ordenamiento según demanda total
Número de tipos de cajas distintos: 100
Costo packaging: 27798426.77999998
Costo flete: 161177250
Costo total: 188975676.77999997
Utilización de pallet promedio: 0.9173906301282783
Utilización de caja promedio: 0.9909932556596077
Ahorro costo total: 9.68261%

In [25]:
cajas, productos, asignaciones_por_producto = guardar_cajas_y_productos()
lista_productos_ordenados = ordenar_por_demanda_total(productos)

solucion_greedy6 = solucion_greedy(cajas, lista_productos_ordenados, asignaciones_por_producto, 
                                   criterio_greedy="minimizar_costo_flete",
                                   titulo_solucion="Greedy minimizando costo flete | Ordenamiento según demanda total")
soluciones_greedy.append(solucion_greedy6)
solucion_greedy6.resumen_general()

Situación original
--------------------------------------------------
Número de tipos de cajas distintos: 204
Costo packaging: 30166293.939999998
Costo flete: 179068800
Costo total: 209235093.94
Utilización de pallet promedio: 0.8320794116391749
Utilización de caja promedio: 1.0

Situación nueva
--------------------------------------------------
Grosor elegido: 3mm
Criterio elegido: Greedy minimizando costo flete | Ordenamiento según demanda total
Número de tipos de cajas distintos: 182
Costo packaging: 28691260.799999986
Costo flete: 161171250
Costo total: 189862510.79999998
Utilización de pallet promedio: 0.9102406754058984
Utilización de caja promedio: 0.9989024157619196
Ahorro costo total: 9.25876%

In [26]:
cajas, productos, asignaciones_por_producto = guardar_cajas_y_productos()
lista_productos_ordenados = ordenar_por_demanda_total(productos)

solucion_greedy7 = solucion_greedy(cajas, lista_productos_ordenados, asignaciones_por_producto, 
                                   criterio_greedy="maximizar_utilizacion_pallet",
                                   titulo_solucion="Greedy maximizando utilizacion pallet | Ordenamiento según demanda total")
soluciones_greedy.append(solucion_greedy7)
solucion_greedy7.resumen_general()

Situación original
--------------------------------------------------
Número de tipos de cajas distintos: 204
Costo packaging: 30166293.939999998
Costo flete: 179068800
Costo total: 209235093.94
Utilización de pallet promedio: 0.8320794116391749
Utilización de caja promedio: 1.0

Situación nueva
--------------------------------------------------
Grosor elegido: 3mm
Criterio elegido: Greedy maximizando utilizacion pallet | Ordenamiento según demanda total
Número de tipos de cajas distintos: 76
Costo packaging: 27406334.340000004
Costo flete: 161380650
Costo total: 188786984.34
Utilización de pallet promedio: 0.9593515126880588
Utilización de caja promedio: 0.9445527162171292
Ahorro costo total: 9.77279%

In [27]:
cajas, productos, asignaciones_por_producto = guardar_cajas_y_productos()
lista_productos_ordenados = ordenar_por_demanda_total(productos)

solucion_greedy8 = solucion_greedy(cajas, lista_productos_ordenados, asignaciones_por_producto, 
                                   criterio_greedy="maximizar_volumen_tipo",
                                   titulo_solucion="Greedy maximizando volumen caja | Ordenamiento según demanda total")
soluciones_greedy.append(solucion_greedy8)
solucion_greedy8.resumen_general()

Situación original
--------------------------------------------------
Número de tipos de cajas distintos: 204
Costo packaging: 30166293.939999998
Costo flete: 179068800
Costo total: 209235093.94
Utilización de pallet promedio: 0.8320794116391749
Utilización de caja promedio: 1.0

Situación nueva
--------------------------------------------------
Grosor elegido: 3mm
Criterio elegido: Greedy maximizando volumen caja | Ordenamiento según demanda total
Número de tipos de cajas distintos: 56
Costo packaging: 27296711.4
Costo flete: 168744900
Costo total: 196041611.4
Utilización de pallet promedio: 0.8914661808554665
Utilización de caja promedio: 0.9766131894269261
Ahorro costo total: 6.30558%

#### **Comparación de criterios**

Finalmente, comparemos todos los criterios Greedy aplicados, y veamos cuál es el que obtuvo mejor ahorro con respecto a la situación base de AlixPartners.

In [28]:
datos = []
    
datos.append({
    'solucion': 'Base',
    'grosor_mm': 3,
    'tipos_cajas': 204,
    'costo_packaging': 30166293.939999998,
    'costo_flete': 179068800,
    'costo_total': 209235093.94,
    'ahorro_%': 0.00000,
    'utilizacion_pallet_promedio': 0.8320794116391749,
    'utilizacion_caja_promedio': 1.0
})
    
for sol in soluciones_greedy:
    datos.append({
        'solucion': sol.titulo,
        'grosor_mm': sol.grosor_elegido,
        'tipos_cajas': sol.cantidad_tipos_cajas,
        'costo_packaging': sol.costo_packaging(),
        'costo_flete': sol.costo_flete(),
        'costo_total': sol.costo_total(),
        'ahorro_%': sol.ahorro_total_porcent() * 100,
        'utilizacion_pallet_promedio': sol.utilizacion_pallet_promedio(),
        'utilizacion_caja_promedio': sol.utilizacion_caja_promedio()
    })

df_comparacion = pd.DataFrame(datos)
df_comparacion

,solucion,grosor_mm,tipos_cajas,costo_packaging,costo_flete,costo_total,ahorro_%,utilizacion_pallet_promedio,utilizacion_caja_promedio
0,Base,3,204,30166293.94,179068800,2.092351e+08,0.000000,0.832079,1.000000
1,Greedy minimizando costo total | Ordenamiento ...,3,119,27791103.60,161188350,1.889795e+08,9.680804,0.917755,0.990524
2,Greedy minimizando costo flete | Ordenamiento ...,3,182,28691260.80,161171250,1.898625e+08,9.258764,0.910241,0.998902
3,Greedy maximizando utilizacion pallet | Ordena...,3,76,27406334.34,161380650,1.887870e+08,9.772792,0.959352,0.944553
4,Greedy maximizando volumen caja | Ordenamiento...,3,50,27329547.18,167754600,1.950841e+08,6.763180,0.896106,0.972244
5,Greedy minimizando costo total | Ordenamiento ...,3,100,27798426.78,161177250,1.889757e+08,9.682610,0.917391,0.990993
6,Greedy minimizando costo flete | Ordenamiento ...,3,182,28691260.80,161171250,1.898625e+08,9.258764,0.910241,0.998902
7,Greedy maximizando utilizacion pallet | Ordena...,3,76,27406334.34,161380650,1.887870e+08,9.772792,0.959352,0.944553
8,Greedy maximizando volumen caja | Ordenamiento...,3,56,27296711.40,168744900,1.960416e+08,6.305578,0.891466,0.976613

In [29]:
nombre_mejor = df_comparacion.loc[df_comparacion['costo_total'].idxmin(), 'solucion']

if nombre_mejor == 'Base':
    mejor_sol = None  # la base no es un objeto Solucion, es tu caso original
else:
    mejor_sol = next(s for s in soluciones_greedy if s.titulo == nombre_mejor)

print(f"Mejor solución: {nombre_mejor}, costo total: {df_comparacion['costo_total'].min()}")

Mejor solución: Greedy maximizando utilizacion pallet | Ordenamiento según #cajas asignables, costo total: 188786984.33999997

In [30]:
mejor_sol.exportar_submmit(nombre_csv="7-greedy_3mm_mejor_sol_mas_cajas")